Repository elementor/elementor, pull requests merged in 2025-06, with the labels that each got.

#31369 Tweak: Make the repeater control use list role for improved accessibility [ED-19428]
  assets/dev/js/editor/controls/repeater-row.js
  core/kits/controls/repeater.php
  includes/controls/repeater.php
Labels: run-tests

#31426 Revert "Fix: [V4] Fix: Div block/Flex box 'Overflow-hidden' hides the widget handles [ED-18934]"
  assets/dev/js/editor/elements/views/base.js
Labels: run-tests

#31444 Fix: Google Fonts with long file names are not loaded (#30748) [ED-19435]
  core/files/fonts/google-font.php
Labels: run-tests

#31461 Internal: Test
  .github/workflows/cherry-pick-pr.yml
Labels: cp_3.30, cp_3.29

#31479 internal: Fix
  .github/workflows/cherry-pick-pr.yml
Labels: cp_3.30, cp_3.29

#31480 Fix : origina
  .github/workflows/cherry-pick-pr.yml
Labels: cp_3.30

#31481 Fix: 1
  .github/workflows/cherry-pick-pr.yml
Labels: cp_3.30

#31492 CP1
  .github/workflows/cherry-pick-pr.yml
  pull_request.json
Labels: cp_3.30

#31493 cp2
  .github/workflows/cherry-pick-pr.yml
Labels: cp_3.30

#31494 cp4
  .github/workflows/cherry-pick-pr.yml
Labels: cp_3.30

#31498 Fix: Vertical alignment for the Icon Box Position does not work on mobile [ED-19571]
  assets/dev/scss/frontend/widgets/icon-box.scss
  includes/widgets/icon-box.php
Labels: run-tests

#31505 Tweak: Remove background videos from the accessibility tree [ED-19580]
  includes/elements/container.php
  includes/elements/section.php
Labels: run-tests

#31509 permissions
  .github/workflows/cherry-pick-pr.yml
Labels: cp_3.29

#31510 Permissions1
  .github/workflows/cherry-pick-pr.yml
Labels: cp_3.30

#31511 change user
  .github/workflows/cherry-pick-pr.yml
Labels: cp_3.30

#31502 Internal: Style tab test: display the last open sections [ED-19376]
  tests/playwright/sanity/modules/v4-tests/editing-panel-tabs.test.ts
  tests/playwright/sanity/modules/v4-tests/editing-panel-tabs.test.ts-snapshots/style-tab-last-open-sections-linux.png
Labels: run-tests

#31516 Internal: The import/Export close button returns to the last position [ED-19560]
  app/assets/js/layout/header.js
  app/assets/js/layout/page.js
  app/modules/import-export/assets/js/pages/export/export-kit/components/kit-information/components/kit-name/kit-name.js
  app/modules/import-export/assets/js/templates/layout.js
  app/modules/kit-library/assets/js/models/taxonomy.js
Labels: 1 min review

#31537 Fix: Clean up variables TODO [ED-16053]
  modules/variables/classes/style-transformers.php
  modules/variables/storage/repository.php
  tests/phpunit/elementor/modules/variables/classes/test-variable-repository.php
Labels: 1 min review

#31525 Internal: Add cherry-pick PR workflow with automated cherry-picking
  .github/workflows/cherry-pick-pr.yml
Labels: cp_3.30, cp_3.29, missing-jira, 🚨 1 Unresolved Thread(s), 5 min review

#31536 Internal: Remove `direction.scss` file [ED-19617]
  .grunt-config/widgets-css.js
  assets/dev/scss/direction/admin-rtl.scss
  assets/dev/scss/direction/admin.scss
  assets/dev/scss/direction/app-base-rtl.scss
  assets/dev/scss/direction/app-base.scss
  assets/dev/scss/direction/app-rtl.scss
  assets/dev/scss/direction/app.scss
  assets/dev/scss/direction/common-rtl.scss
  assets/dev/scss/direction/common.scss
  assets/dev/scss/direction/editor-preview-rtl.scss
  assets/dev/scss/direction/editor-preview.scss
  assets/dev/scss/direction/editor-rtl.scss
  assets/dev/scss/direction/editor.scss
  assets/dev/scss/direction/frontend-rtl.scss
  assets/dev/scss/direction/frontend.scss
  assets/dev/scss/editor/_mode-switcher.scss
  assets/dev/scss/editor/panel/panel.scss
  assets/dev/scss/editor/preview/preview.scss
  assets/dev/scss/global/global.scss
  assets/dev/scss/helpers/direction.scss
  assets/dev/scss/helpers/mixins.scss
  modules/admin-top-bar/assets/scss/admin.scss
Labels: run-tests, 1 min review, 🗑️ Deleted files

#31482 Tweak: Replaced select control with visual choose control in Shape Dividers [ED-19553]
  assets/dev/scss/editor/panel/_controls.scss
  includes/elements/container.php
  includes/elements/section.php
  includes/shapes.php
Labels: run-tests, 1 min review

#30366 Internal: Deleting all landing pages doesn't hide the deprecated landing pages feature [ED-18354]
  modules/landing-pages/module.php
Labels: 1 min review

#31558 Internal: Rename kits to website templates cont' [ED-19488]
  app/modules/import-export/assets/js/admin.js
  app/modules/import-export/assets/js/pages/export/export-kit/components/kit-information/components/kit-info-modal/kit-info-modal.js
  app/modules/import-export/assets/js/pages/export/export-kit/components/kit-information/components/kit-name/kit-name.js
  app/modules/import-export/assets/js/shared/process-failed-dialog/process-failed-dialog.js
  app/modules/kit-library/assets/js/components/envato-promotion.js
  app/modules/kit-library/assets/js/components/kit-cloud-delete-dialog.js
  app/modules/kit-library/assets/js/pages/cloud/cloud.js
  app/modules/kit-library/assets/js/pages/favorites/favorites.js
  modules/cloud-library/module.php
  tests/jest/unit/app/modules/import-export/assets/js/admin.test.js
Labels: cp_3.30, 5 min review, 🗑️ Deleted files

#31571 Internal: Update create kit route to use signed URL [ED-19641]
  modules/cloud-kit-library/connect/cloud-kits.php
Labels: 1 min review

#31572 Internal: Update create kit route to use signed URL [ED-19641]
  app/modules/kit-library/connect/cloud-kits.php
Labels: 1 min review

#31582 Internal: Cloud Kits - Connect & Upgrade [ED-19624]
  app/modules/import-export/module.php
  app/modules/kit-library/assets/js/app.js
  app/modules/kit-library/assets/js/context/connect-state-context.js
  app/modules/kit-library/assets/js/hooks/use-cloud-kits-eligibility.js
  app/modules/kit-library/assets/js/hooks/use-connect-state.js
  app/modules/kit-library/assets/js/hooks/use-menu-items.js
  app/modules/kit-library/assets/js/pages/cloud/cloud.js
  app/modules/kit-library/assets/js/pages/cloud/connect-screen.js
  app/modules/kit-library/assets/js/pages/cloud/full-page-loader.js
  app/modules/kit-library/assets/js/pages/cloud/upgrade-screen.js
  app/modules/kit-library/assets/js/pages/favorites/favorites.js
  app/modules/kit-library/assets/js/pages/index/index.scss
Labels: cp_3.30, 20 min review

#31577 Internal: Divider widget > Add V4 Playwright test [ED-19681]
  tests/playwright/sanity/modules/v4-tests/atomic-widgets.test.ts
  tests/playwright/sanity/modules/v4-tests/atomic-widgets.test.ts-snapshots/e-divider-editor-linux.png
  tests/playwright/sanity/modules/v4-tests/atomic-widgets.test.ts-snapshots/e-divider-published-linux.png
  tests/playwright/sanity/modules/v4-tests/atomic-widgets.test.ts-snapshots/widgets-panel-linux.png
  tests/playwright/selectors/editor-selectors.ts
Labels: run-tests

#31532 Internal: Bump packages versions [ED-19410]
  package-lock.json
  package.json
Labels: run-tests, 1 min review

#31574 New: Add changed prop name to atomic element setting history [ED-18712]
  modules/atomic-widgets/elements/atomic-button/atomic-button.php
  modules/atomic-widgets/elements/atomic-heading/atomic-heading.php
  modules/atomic-widgets/elements/atomic-image/atomic-image.php
  modules/atomic-widgets/elements/atomic-paragraph/atomic-paragraph.php
  modules/atomic-widgets/elements/atomic-svg/atomic-svg.php
  modules/atomic-widgets/elements/div-block/div-block.php
Labels: 1 min review

#31557 Internal: [V4] Disable HTML tag control when there's a link [ED-18550]
  modules/atomic-widgets/elements/div-block/div-block.php
  modules/atomic-widgets/prop-dependencies/manager.php
  modules/atomic-widgets/prop-types/base/plain-prop-type.php
  tests/phpunit/elementor/modules/atomic-widgets/dynamic-tags/test-dynamic-tags-module.php
Labels: 1 min review, 🚨 1 Unresolved Thread(s)

#31583 Fix: Can't Drag & Drop in v4 empty view containers [ED-19607]
  modules/atomic-widgets/assets/js/editor/div-block-view.js
  tests/playwright/sanity/modules/div-block/div-block.test.ts
Labels: 🚨 2 Unresolved Thread(s), 5 min review

#31597 Fix: Style controls are not affecting the video iframe in YouTube element [ED-19555]
  modules/atomic-widgets/elements/atomic-youtube/atomic-youtube.php
Labels: 1 min review

#31596 Internal: Replace SASS direction-based styling with native CSS solution [ED-19656]
  assets/dev/scss/editor/panel/_controls.scss
  includes/controls/section.php
  includes/editor-templates/panel-elements.php
  includes/editor-templates/panel.php
Labels: run-tests, 1 min review

#31601 Fix: Woocommerce hint shown when not installed CP [APP-1416][ED-19620]
  core/admin/admin-notices.php
Labels: 1 min review

#31602 Fix: Woocommerce hint shown when not installed CP [APP-1416][ED-19620]
  core/admin/admin-notices.php
Labels: 1 min review, 🚨 1 Unresolved Thread(s)

#31608 Internal: Update cloud-kits.php
  modules/cloud-kit-library/connect/cloud-kits.php
Labels: 1 min review, missing-jira

#31619 Internal: [V4] support nested prop dependencies [ED-19709]
  modules/atomic-widgets/prop-types/base/plain-prop-type.php
  modules/atomic-widgets/prop-types/link-prop-type.php
Labels: 1 min review, 🚨 2 Unresolved Thread(s)

#31616 Internal: Fix Editing panel tabs test wait for element to be loaded [ED-19704]
  tests/playwright/config/timeouts.ts
  tests/playwright/sanity/modules/v4-tests/editing-panel-tabs.test.ts
Labels: run-tests, 1 min review

#31518 Internal: Import/Export Themes [ED-19570]
  app/modules/import-export/processes/import.php
  app/modules/import-export/runners/export/site-settings.php
  app/modules/import-export/runners/import/site-settings.php
  app/modules/import-export/runners/revert/site-settings.php
  tests/phpunit/elementor/app/import-export/mock/sample-kit.zip
  tests/phpunit/elementor/app/import-export/processes/test-export.php
  tests/phpunit/elementor/app/import-export/processes/test-import.php
  tests/phpunit/elementor/app/import-export/processes/test-revert.php
  tests/phpunit/elementor/app/import-export/test-module.php
Labels: 10 min review, 🚨 6 Unresolved Thread(s)

#31643 Internal: Update deps and fix deps issue
  core/editor/loader/v2/editor-v2-loader.php
  modules/atomic-widgets/module.php
  package-lock.json
  package.json
Labels: run-tests, 1 min review, missing-jira

#31624 Internal: Lazy Load Background Images feature hides background images in the editor [ED-19717]
  modules/lazyload/module.php
Labels: run-tests, 1 min review

#31649 Internal: Fix CI compatibility issue with older Elementor Pro versions [ED-19767]
  assets/dev/scss/helpers/direction.scss
Labels: run-tests

#31659 Internal: General i18n improvements [ED-19776]
  app/modules/import-export-customization/module.php
  app/modules/import-export/module.php
  includes/widgets/rating.php
  includes/widgets/traits/button-trait.php
  modules/floating-buttons/base/widget-contact-button-base.php
  modules/floating-buttons/classes/render/contact-buttons-render-base.php
  modules/floating-buttons/classes/render/floating-bars-core-render.php
  modules/floating-buttons/module.php
  modules/link-in-bio/base/widget-link-in-bio-base.php
  modules/promotions/admin-menu-items/custom-icons-promotion-item.php
  modules/promotions/admin-menu-items/form-submissions-promotion-item.php
  modules/promotions/widgets/pro-widget-promotion.php
Labels: run-tests, 5 min review

#31660 Tweak: Added new `lh` and `rlh` CSS units to Typography Line Height control [ED-19604]
  includes/controls/groups/typography.php
Labels: run-tests, 1 min review

#31658 Tweak: Activated "Element Caching" experiment for all sites [ED-19733]
  modules/element-cache/module.php
Labels: run-tests, 1 min review

#31654 Tweak: Promoted "Optimized Markup" feature to Stable status and activated for all sites [ED-19768]
  core/experiments/manager.php
Labels: run-tests, 1 min review
