Repository elementor/elementor, pull requests merged in 2025-09, with the labels that each got.

#32484 Internal: Add service and api actions for batch save in the Variable Manager [ED-20408]
  modules/variables/storage/repository.php
  packages/packages/core/editor-variables/src/__tests__/batch-operations.test.ts
  packages/packages/core/editor-variables/src/api.ts
  packages/packages/core/editor-variables/src/batch-operations.ts
  packages/packages/core/editor-variables/src/components/variables-manager/variables-manager-panel.tsx
  packages/packages/core/editor-variables/src/service.ts
Labels: 🚨 2 Unresolved Thread(s), 30 min review

#32564 Fix: Update size variable empty state [ED-20460]
  packages/packages/core/editor-variables/src/components/__tests__/variable-selection.test.tsx
  packages/packages/core/editor-variables/src/components/ui/empty-state.tsx
  packages/packages/core/editor-variables/src/components/variables-selection.tsx
  packages/packages/core/editor-variables/src/hooks/use-prop-variables.ts
Labels: 🚨 2 Unresolved Thread(s), 30 min review

#32566 Internal: Update icon library version [TMZ-409]
  assets/lib/eicons/css/elementor-icons.css
  assets/lib/eicons/css/elementor-icons.min.css
  assets/lib/eicons/eicons.json
  assets/lib/eicons/fonts/eicons.eot
  assets/lib/eicons/fonts/eicons.svg
  assets/lib/eicons/fonts/eicons.ttf
  assets/lib/eicons/fonts/eicons.woff
  assets/lib/eicons/fonts/eicons.woff2
  includes/managers/icons.php
Labels: 1 min review, cp_3.32

#32537 Internal: Add attributes and keys escaping [ED-20438]
  packages/packages/core/editor-canvas/src/transformers/settings/attributes-transformer.ts
  packages/packages/libs/editor-controls/src/controls/__tests__/key-value-control.test.tsx
  packages/packages/libs/editor-controls/src/controls/key-value-control.tsx
  packages/packages/libs/editor-controls/src/utils/__tests__/escape-html-attr.test.ts
  packages/packages/libs/editor-controls/src/utils/escape-html-attr.ts
Labels: 5 min review

#32565 Internal: Add dynamic tag for shortcode [ED-20483]
  modules/atomic-widgets/dynamic-tags/dynamic-tags-editor-config.php
  modules/atomic-widgets/dynamic-tags/dynamic-tags-schemas.php
Labels: 1 min review

#32575 Fix: Control text color should override kits text color [ED-20089]
  modules/floating-buttons/assets/scss/floating-bars/widgets/floating-bars-base.scss
Labels: 1 min review, cp_3.32

#32580 Tweak: Reduce gap between elements in Effects style section. [ED-20430]
  app/modules/import-export-customization/assets/js/export/pages/export-complete.js
  app/modules/import-export-customization/assets/js/shared/hooks/use-pages.js
  app/modules/import-export/assets/js/hooks/use-kit.js
  app/modules/import-export/assets/js/hooks/use-plugins-data.js
  app/modules/import-export/assets/js/hooks/use-plugins.js
  app/modules/import-export/assets/js/pages/export/export-kit/export-kit.js
  app/modules/import-export/assets/js/pages/export/export-plugins/export-plugins.js
  app/modules/kit-library/assets/js/hooks/use-taxonomies.js
  packages/packages/core/editor-editing-panel/src/components/style-sections/effects-section/effects-section.tsx
Labels: 1 min review

#32596 Internal: Pass action payload from repeater [ED-20675]
  packages/packages/libs/editor-controls/src/bound-prop-context/prop-context.tsx
  packages/packages/libs/editor-controls/src/components/__tests__/repeater.test.tsx
  packages/packages/libs/editor-controls/src/components/repeater.tsx
  packages/packages/libs/editor-controls/src/index.ts
Labels: 20 min review

#32547 Internal: Handling already existing classes in the be (BE only) [ED-20139]
  core/utils/api/error-builder.php
  core/utils/api/response-builder.php
  modules/global-classes/global-classes-parser.php
  modules/global-classes/global-classes-rest-api.php
  tests/phpunit/elementor/modules/global-classes/test-global-classes-rest-api.php
Labels: 30 min review, 🚨 12 Unresolved Thread(s)

#32602 Fix: Revert deletion of used script
  .github/scripts/repo-utils.js
Labels: missing-jira, 10 min review

#32603 Fix: Revert used script delete
  .github/scripts/repo-utils.js
Labels: missing-jira, 10 min review

#32608 Internal: Update php coding standard - Spacing [ED-20691]
  core/common/modules/connect/apps/common-app.php
  core/files/css/base.php
  core/utils/hints.php
  includes/template-library/classes/class-import-images.php
  includes/template-library/manager.php
  includes/template-library/sources/local.php
  modules/favorites/module.php
  modules/floating-buttons/classes/render/contact-buttons-render-base.php
  modules/floating-buttons/module.php
  modules/global-classes/usage/document-usage.php
  modules/link-in-bio/classes/render/render-base.php
  modules/system-info/reporters/network-plugins.php
  modules/variables/storage/repository.php
  tests/bootstrap.php
Labels: 5 min review

#32611 Fix: BC Issue with uninitialized parameter [ED-20690]
  modules/atomic-widgets/controls/types/repeatable-control.php
Labels: run-tests, 1 min review

#32609 Internal: Update php coding standard - Underscore [ED-20693]
  ruleset.xml
Labels: 1 min review

#32629 Fix: Missing import runners [ED-20706]
  modules/global-classes/import-export-customization/import-export-customization.php
  modules/global-classes/import-export-customization/runners/export.php
  modules/global-classes/import-export-customization/runners/import.php
  modules/global-classes/module.php
  modules/kit-elements-defaults/import-export-customization/import-export-customization.php
  modules/kit-elements-defaults/import-export-customization/runners/export.php
  modules/kit-elements-defaults/import-export-customization/runners/import.php
  modules/kit-elements-defaults/module.php
  tests/phpunit/elementor/modules/global-classes/import-export-customization/mocks/invalid/global-classes.json
  tests/phpunit/elementor/modules/global-classes/import-export-customization/mocks/valid/global-classes.json
  tests/phpunit/elementor/modules/global-classes/import-export-customization/test-export-runner.php
  tests/phpunit/elementor/modules/global-classes/import-export-customization/test-imort-runner.php
  tests/phpunit/elementor/modules/kit-elements-defaults/import-export-customization/runners/mock/kit-elements-defaults.json
  tests/phpunit/elementor/modules/kit-elements-defaults/import-export-customization/runners/mock/mock-control-kits-defaults.php
  tests/phpunit/elementor/modules/kit-elements-defaults/import-export-customization/runners/mock/mock-widget-kits-defaults.php
  tests/phpunit/elementor/modules/kit-elements-defaults/import-export-customization/runners/test-export.php
  tests/phpunit/elementor/modules/kit-elements-defaults/import-export-customization/runners/test-import.php
Labels: 30 min review, cp_3.32

#32619 Internal: Custom CSS Move code to elementor-pro repo-remove code [ED-20531]
  packages/packages/core/editor-editing-panel/src/components/custom-css-field.tsx
  packages/packages/core/editor-editing-panel/src/components/custom-css.tsx
  packages/packages/core/editor-editing-panel/src/components/style-tab.tsx
  packages/packages/core/editor-editing-panel/src/index.ts
  packages/packages/core/editor-global-classes/src/index.ts
  packages/packages/libs/editor-controls/src/components/css-code-editor/__tests__/css-editor.test.tsx
  packages/packages/libs/editor-controls/src/components/css-code-editor/__tests__/visual-content-change-protection.test.ts
  packages/packages/libs/editor-controls/src/components/css-code-editor/css-editor.styles.ts
  packages/packages/libs/editor-controls/src/components/css-code-editor/css-editor.tsx
  packages/packages/libs/editor-controls/src/components/css-code-editor/css-validation.ts
  packages/packages/libs/editor-controls/src/components/css-code-editor/resize-handle.tsx
  packages/packages/libs/editor-controls/src/components/css-code-editor/visual-content-change-protection.ts
  packages/packages/libs/editor-controls/src/index.ts
Labels: 5 min review, 🗑️ Deleted files

#32589 Internal: Variables manager base tests [ED-20641]
  packages/packages/core/editor-editing-panel/src/components/style-sections/typography-section/text-color-field.tsx
  packages/packages/core/editor-variables/src/components/fields/color-field.tsx
  packages/packages/core/editor-variables/src/components/fields/font-field.tsx
  packages/packages/core/editor-variables/src/components/variable-creation.tsx
  packages/packages/core/editor-variables/src/components/variables-selection.tsx
  packages/packages/libs/editor-controls/src/components/item-selector.tsx
  packages/packages/libs/editor-controls/src/controls/color-control.tsx
  packages/packages/libs/editor-controls/src/controls/font-family-control/font-family-control.tsx
  packages/packages/libs/editor-ui/src/components/popover/body.tsx
  packages/packages/libs/editor-ui/src/components/popover/search.tsx
  tests/playwright/playwright.config.ts
  tests/playwright/sanity/modules/v4-tests/editor-variables/base.fixture.ts
  tests/playwright/sanity/modules/v4-tests/editor-variables/utils.ts
  tests/playwright/sanity/modules/v4-tests/editor-variables/variable-manager.test.ts
Labels: 🚨 4 Unresolved Thread(s), 20 min review, 🗑️ Deleted files

#32623 Internal: Fix editor settings title change condition [ED-20704]
  assets/dev/js/editor/regions/navigator/element.js
Labels: 1 min review

#32615 Internal: Fix publish packages at one click release [ED-20698]
  .github/workflows/one-click-release.yml
Labels: 1 min review, cp_3.32

#32573 New: Components tab: add component using d&d [ED-20425]
  assets/dev/js/editor/views/base-container.js
  packages/package-lock.json
  packages/packages/core/editor-canvas/src/index.ts
  packages/packages/core/editor-canvas/src/sync/drag-element-from-panel.ts
  packages/packages/core/editor-canvas/src/sync/types.ts
  packages/packages/core/editor-components/package.json
  packages/packages/core/editor-components/src/components/__tests__/create-component-form.test.tsx
  packages/packages/core/editor-components/src/components/components-tab.tsx
  packages/packages/core/editor-components/src/components/create-component-form/create-component-form.tsx
  packages/packages/core/editor-components/src/components/create-component-form/utils/replace-element-with-component.ts
Labels: 10 min review, 🚨 7 Unresolved Thread(s)

#32570 CI: Remove several stuff for CI optimizations [ED-20722]
  .grunt-config/bumpup.js
  .grunt-config/copy.js
  .grunt-config/webpack.js
  Gruntfile.js
  package-lock.json
  package.json
Labels: run-tests, 1 min review, 🗑️ Deleted files

#32553 Internal: Create the basic e2e playwright test [ED-20640]
  package.json
  packages/packages/core/editor-editing-panel/src/components/style-sections/typography-section/text-color-field.tsx
  packages/packages/core/editor-variables/src/components/fields/color-field.tsx
  packages/packages/core/editor-variables/src/components/fields/font-field.tsx
  packages/packages/core/editor-variables/src/components/variable-creation.tsx
  packages/packages/core/editor-variables/src/components/variables-selection.tsx
  packages/packages/libs/editor-controls/src/components/item-selector.tsx
  packages/packages/libs/editor-controls/src/controls/color-control.tsx
  packages/packages/libs/editor-controls/src/controls/font-family-control/font-family-control.tsx
  packages/packages/libs/editor-ui/src/components/popover/body.tsx
  packages/packages/libs/editor-ui/src/components/popover/search.tsx
  tests/playwright/sanity/modules/v4-tests/editor-variables/utils.ts
  tests/playwright/sanity/modules/v4-tests/editor-variables/variable-manager.test.ts
  tests/playwright/sanity/modules/v4-tests/editor-variables/variables-manager-template.json
  tests/playwright/selectors/editor-selectors.ts
Labels: 5 min review, 20 min review, 🚨 7 Unresolved Thread(s)

#32654 Internal: Changelog for v3.31.4
  changelog.txt
  readme.txt
Labels: 1 min review

#32653 Internal: Set working directory for publish packages [ED-20698]
  .github/workflows/one-click-release.yml
Labels: 1 min review, cp_3.32

#32652 Tweak: Add promotions to core and pro [ED-20573]
  app/modules/import-export-customization/assets/js/import/context/import-context.js
  app/modules/import-export-customization/assets/js/import/utils/version-utils.js
  app/modules/import-export-customization/assets/js/shared/components/kit-parts-selection.js
  app/modules/import-export-customization/assets/js/shared/components/re-export-banner.js
  app/modules/import-export-customization/assets/js/shared/components/upgrade-version-banner.js
  app/modules/import-export-customization/module.php
  tests/jest/unit/app/modules/import-export-customization/utils/version-utils.test.js
Labels: 20 min review

#32660 Fix: Import export customization visual QA [ED-20659]
  app/assets/js/utils/utils.js
  app/modules/import-export-customization/assets/js/export/components/export-intro.js
  app/modules/import-export-customization/assets/js/export/components/kit-info.js
  app/modules/import-export-customization/assets/js/import/pages/import-customization.js
  app/modules/import-export-customization/assets/js/shared/components/customization-list-setting-section.js
  app/modules/import-export-customization/assets/js/shared/components/customization-setting-section.js
  app/modules/import-export-customization/assets/js/shared/components/kit-customization-dialog.js
  app/modules/import-export-customization/assets/js/shared/components/kit-parts-selection.js
  app/modules/import-export-customization/assets/js/shared/components/kit-plugins-customization-dialog.js
  app/modules/import-export-customization/assets/js/shared/components/layout/page-header.js
Labels: 10 min review, cp_3.32

#32672 Internal: Marketing - Free trial popup show only to admin [ED-20896]
  modules/pro-free-trial-popup/module.php
Labels: 1 min review, 🚨 1 Unresolved Thread(s)

#32612 Fix: Handle components created from top-level elements [ED-20695]
  packages/packages/libs/editor-elements/src/sync/__tests__/replace-element.test.ts
  packages/packages/libs/editor-elements/src/sync/replace-element.ts
Labels: 10 min review, 🚨 2 Unresolved Thread(s)

#32679 Fix: Fatal error when no promotion widgets are set [ED-20905]
  core/editor/loader/common/editor-common-scripts-settings.php
Labels: run-tests, 1 min review

#32685 Internal: Changelog for GA on main [ED-20916]
  changelog.txt
  readme.txt
Labels: 1 min review

#32666 Internal: Components tab UI ( List, Loading, Empty ) [ED-20423]
  packages/packages/core/editor-components/src/components/__tests__/components-tab.test.tsx
  packages/packages/core/editor-components/src/components/__tests__/create-component-form.test.tsx
  packages/packages/core/editor-components/src/components/components-item.tsx
  packages/packages/core/editor-components/src/components/components-list.tsx
  packages/packages/core/editor-components/src/components/components-tab.tsx
  packages/packages/core/editor-components/src/components/components.tsx
  packages/packages/core/editor-components/src/components/loading-components.tsx
  packages/packages/core/editor-components/src/init.ts
Labels: 🗑️ Deleted files, 30 min review

#32698 Fix: Issue intorduced by 32679 [ED-20919]
  core/editor/loader/common/editor-common-scripts-settings.php
Labels: run-tests, 1 min review, cp_3.31, cp_3.32

#32702 Internal: Fix Off sync 3.3.1 to main [ED-19619]
  core/editor/loader/common/editor-common-scripts-settings.php
Labels: run-tests

#32696 Tweak: Update supported browsers [ED-20927]
  .browserslistrc
  .grunt-config/webpack.js
Labels: 1 min review

#32705 Internal: Save local state by breakpoint, customcss [ED-20928]
  packages/packages/core/editor-editing-panel/src/components/__tests__/style-tab.test.tsx
  packages/packages/core/editor-editing-panel/src/hooks/use-custom-css.ts
Labels: 1 min review

#32706 Internal: Revert "Optimized Markup" activation for all websites [ED-20950]
  core/admin/admin-notices.php
  core/experiments/manager.php
Labels: run-tests, 1 min review, cp_3.32

#32688 Internal: Create element field with initial tabs control [ED-20433]
  modules/atomic-widgets/elements/atomic-tabs/atomic-tab-panel.php
  modules/atomic-widgets/elements/atomic-tabs/atomic-tab.php
  modules/atomic-widgets/elements/atomic-tabs/atomic-tabs-content.php
  modules/atomic-widgets/elements/atomic-tabs/atomic-tabs-list.php
  packages/packages/core/editor-editing-panel/src/controls-registry/element-controls/__tests__/get-element-by-type.test.ts
  packages/packages/core/editor-editing-panel/src/controls-registry/element-controls/get-element-by-type.ts
  packages/packages/core/editor-editing-panel/src/controls-registry/element-controls/tabs-control/actions.ts
  packages/packages/core/editor-editing-panel/src/controls-registry/element-controls/tabs-control/tabs-control.tsx
  packages/packages/libs/editor-controls/src/bound-prop-context/prop-context.tsx
  packages/packages/libs/editor-controls/src/components/__tests__/repeater.test.tsx
  packages/packages/libs/editor-controls/src/components/repeater.tsx
  packages/packages/libs/editor-controls/src/index.ts
  packages/packages/libs/editor-elements/src/hooks/use-element-children.ts
  packages/packages/libs/editor-elements/src/hooks/use-element-editor-settings.ts
  packages/packages/libs/editor-elements/src/index.ts
  packages/packages/libs/editor-elements/src/sync/__tests__/duplicate-elements.test.ts
  packages/packages/libs/editor-elements/src/sync/duplicate-elements.ts
  packages/packages/libs/editor-elements/src/sync/get-element-editor-settings.ts
  packages/tests/test-utils/create-mock-element-with-children.ts
Labels: 🚨 1 Unresolved Thread(s), 30 min review

#32736 Internal: Revert Cherry-pick PR 32730 to 3.32 Help group in top bar [ED-20977]
  packages/packages/core/editor-app-bar/src/components/locations/main-menu-location.tsx
  packages/packages/core/editor-app-bar/src/locations.ts
Labels: 1 min review

#32731 Internal: Initialize editor settings on elements [ED-20703]
  modules/atomic-widgets/assets/js/editor/atomic-element-model.js
  modules/atomic-widgets/elements/element-builder.php
  modules/atomic-widgets/elements/widget-builder.php
Labels: 1 min review

#32735 Internal: Add error messages for Variables Manager FE [ED-19962]
  packages/packages/core/editor-variables/src/components/fields/label-field.tsx
  packages/packages/core/editor-variables/src/components/variables-manager/hooks/use-auto-edit.ts
  packages/packages/core/editor-variables/src/components/variables-manager/hooks/use-variables-manager-state.ts
  packages/packages/core/editor-variables/src/components/variables-manager/variable-editable-cell.tsx
  packages/packages/core/editor-variables/src/components/variables-manager/variables-manager-panel.tsx
  packages/packages/core/editor-variables/src/components/variables-manager/variables-manager-table.tsx
  packages/packages/core/editor-variables/src/variables-registry/create-variable-type-registry.ts
  packages/packages/libs/editor-ui/src/components/warning-infotip.tsx
Labels: 🚨 1 Unresolved Thread(s), 30 min review

#32745 Internal: Changelog v3.32
  changelog.txt
  readme.txt
Labels: 1 min review

#32721 Internal: Sync the selected element with its type [ED-20970]
  packages/packages/core/editor-editing-panel/src/components/__tests__/editing-panel.test.tsx
  packages/packages/core/editor-editing-panel/src/controls-registry/element-controls/tabs-control/tabs-control.tsx
  packages/packages/libs/editor-elements/src/hooks/__tests__/use-selected-elements.test.ts
  packages/packages/libs/editor-elements/src/hooks/use-element-type.ts
  packages/packages/libs/editor-elements/src/hooks/use-selected-element.ts
  packages/packages/libs/editor-elements/src/index.ts
  packages/packages/libs/editor-elements/src/sync/__tests__/get-element-type.test.ts
  packages/packages/libs/editor-elements/src/sync/get-element-type.ts
Labels: 10 min review, 🗑️ Deleted files

#32750 Internal: Add default tab to tabs control [ED-20502]
  packages/packages/core/editor-editing-panel/src/controls-registry/element-controls/tabs-control/tabs-control.tsx
Labels: 10 min review

#32768 Fix: Full Width Container are not centered aligned [ED-21008] (#32766)
  assets/dev/scss/frontend/_container.scss
Labels: 1 min review

#32738 Internal: [V4] apply new tag value when link is conflicting [ED-19977]
  modules/atomic-widgets/controls/types/html-tag-control.php
  modules/atomic-widgets/controls/types/select-control.php
  modules/atomic-widgets/elements/div-block/div-block.php
  modules/atomic-widgets/elements/flexbox/flexbox.php
  modules/atomic-widgets/prop-dependencies/manager.php
  modules/atomic-widgets/prop-types/link-prop-type.php
  packages/packages/core/editor-editing-panel/src/controls-registry/conditional-field.tsx
  packages/packages/core/editor-editing-panel/src/controls-registry/controls-registry.tsx
  packages/packages/core/editor-editing-panel/src/controls-registry/settings-field.tsx
  packages/packages/core/editor-editing-panel/src/utils/prop-dependency-utils.ts
  packages/packages/libs/editor-controls/src/components/conditional-control-infotip.tsx
  packages/packages/libs/editor-controls/src/controls/html-tag-control.tsx
  packages/packages/libs/editor-controls/src/controls/query-control.tsx
  packages/packages/libs/editor-controls/src/index.ts
  packages/packages/libs/editor-elements/src/sync/get-element-label.ts
  packages/packages/libs/editor-props/src/types.ts
  packages/packages/libs/editor-props/src/utils/__tests__/prop-dependency-utils.test.ts
  packages/packages/libs/editor-props/src/utils/prop-dependency-utils.ts
  tests/phpunit/elementor/modules/atomic-widgets/dynamic-tags/test-dynamic-tags-module.php
  tests/playwright/sanity/modules/atomic-widgets/helper.ts
  tests/playwright/sanity/modules/atomic-widgets/prop-dependencies/link-dependencies.test.ts
Labels: run-tests, 🚨 1 Unresolved Thread(s), 30 min review

#32781 Internal: Changelog for GA on main [ED-21028]
  changelog.txt
  readme.txt
Labels: 1 min review

#32644 Internal: Update the look of the 'Not authorized to upload SVG' alert [ED-20232]
  packages/packages/libs/editor-controls/src/components/conditional-control-infotip.tsx
  packages/packages/libs/editor-controls/src/components/enable-unfiltered-modal.tsx
  packages/packages/libs/editor-controls/src/controls/__tests__/svg-media-control.test.tsx
  packages/packages/libs/editor-controls/src/controls/svg-media-control.tsx
Labels: 5 min review

#32775 Fix: Align color value with design [ED-20915]
  packages/packages/core/editor-variables/src/components/variables-manager/variable-editable-cell.tsx
  packages/packages/core/editor-variables/src/components/variables-manager/variables-manager-table.tsx
  tests/playwright/sanity/modules/v4-tests/editor-variables/utils.ts
  tests/playwright/sanity/modules/v4-tests/editor-variables/variable-manager.test.ts
  tests/playwright/sanity/modules/v4-tests/editor-variables/variable-manager.test.ts-snapshots/color-variable-screenshot-darwin.png
  tests/playwright/sanity/modules/v4-tests/editor-variables/variable-manager.test.ts-snapshots/color-variable-screenshot-linux.png
Labels: run-tests, 5 min review

#32787 Fix: Structure Panel Indicators don't appear on RTL layouts [ED-21040]
  assets/dev/scss/editor/navigator/navigator.scss
Labels: run-tests, 1 min review, cp_3.32

#32808 Internal: Implement Mixpanel events for the new 'one-click download' user flow [ED-20150]
  modules/pro-install/assets/js/pro-install-events.js
  modules/pro-install/pro-install-menu-item.php
Labels: 10 min review

#32820 Fix: Changes in the API-Info break the way several 3rd party plugin serve their templates (#32811)
  includes/api.php
  includes/template-library/manager.php
Labels: 1 min review, missing-jira

#32826 Tweak: Clear Cache after Enabling/Disabling Load Google Fonts Locally (#32795) [ED-21060]
  core/files/fonts/google-font.php
  includes/settings/settings.php
Labels: run-tests, 1 min review, 🚨 2 Unresolved Thread(s)

#32831 Internal: Update env settings [ED-20996]
  .github/workflows/one-click-release.yml
Labels: 1 min review

#32802 Tweak: On export adding the UI for the media [ED-20955]
  app/modules/import-export-customization/assets/js/export/components/export-kit-footer.js
  app/modules/import-export-customization/assets/js/export/components/export-kit-parts-selection.js
  app/modules/import-export-customization/assets/js/export/context/export-context.js
  app/modules/import-export-customization/assets/js/shared/components/customization-list-setting-section.js
  app/modules/import-export-customization/assets/js/shared/components/kit-content-customization-dialog.js
  app/modules/import-export-customization/assets/js/shared/components/kit-parts-selection.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/export/components/export-kit-footer.test.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/export/components/kit-parts-customization.test.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/shared/components/kit-content-customization-dialog.test.js
Labels: 30 min review

#32825 Internal: Variables Manager empty state [ED-19862]
  packages/packages/core/editor-variables/src/components/ui/empty-state.tsx
  packages/packages/core/editor-variables/src/components/ui/no-search-results.tsx
  packages/packages/core/editor-variables/src/components/variables-manager/__tests__/variable-edit-menu.test.tsx
  packages/packages/core/editor-variables/src/components/variables-manager/__tests__/variable-table-cell.test.tsx
  packages/packages/core/editor-variables/src/components/variables-manager/__tests__/variables-manager-table.test.tsx
  packages/packages/core/editor-variables/src/components/variables-manager/ui/variable-edit-menu.tsx
  packages/packages/core/editor-variables/src/components/variables-manager/ui/variable-table-cell.tsx
  packages/packages/core/editor-variables/src/components/variables-manager/variables-manager-create-menu.tsx
  packages/packages/core/editor-variables/src/components/variables-manager/variables-manager-panel.tsx
  packages/packages/core/editor-variables/src/components/variables-manager/variables-manager-table.tsx
  tests/playwright/sanity/modules/v4-tests/editor-variables/utils.ts
  tests/playwright/sanity/modules/v4-tests/editor-variables/variable-manager.test.ts
Labels: run-tests, 5 min review

#32829 Internal: Register tabs control [ED-20393]
  modules/atomic-widgets/base/element-control-base.php
  modules/atomic-widgets/controls/types/elements/tabs-control.php
  modules/atomic-widgets/elements/atomic-tabs/atomic-tabs.php
  modules/atomic-widgets/elements/has-atomic-base.php
  packages/packages/core/editor-editing-panel/src/components/settings-tab.tsx
  packages/packages/core/editor-editing-panel/src/controls-registry/controls-registry.tsx
  packages/packages/core/editor-editing-panel/src/controls-registry/element-controls/tabs-control/actions.ts
  packages/packages/core/editor-editing-panel/src/controls-registry/element-controls/tabs-control/tabs-control.tsx
  packages/packages/libs/editor-elements/src/types.ts
Labels: 🚨 6 Unresolved Thread(s), 20 min review

#32186 Fix: Screenshots generated with issues for Cloud Templates [ED-19232]
  assets/dev/js/editor/components/template-library/views/template/cloud.js
  assets/dev/scss/editor/_templates-modal.scss
  modules/cloud-library/assets/js/preview/screenshot.js
  modules/cloud-library/module.php
  modules/cloud-library/render-mode-preview.php
Labels: 10 min review

#32860 Tweak: Add FE validation when exporting kit name [ED-20918]
  app/modules/import-export-customization/assets/js/export/components/export-kit-footer.js
  app/modules/import-export-customization/assets/js/export/components/kit-info.js
  app/modules/import-export-customization/assets/js/export/context/export-context.js
  app/modules/import-export-customization/assets/js/export/hooks/use-kit-validation.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/export/components/export-kit-footer.test.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/export/context/export-context.test.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/export/hooks/use-kit-validation.test.js
Labels: 30 min review

#32869 Tweak: Add variable Manager Duplicated error message - FE [ED-21087]
  packages/packages/core/editor-variables/src/components/fields/label-field.tsx
  packages/packages/core/editor-variables/src/components/variables-manager/variables-manager-table.tsx
  packages/packages/core/editor-variables/src/utils/validations.ts
Labels: 1 min review

#32812 Internal: Update flows in Onboarding [ED-21019]
  app/modules/onboarding/assets/js/app.js
  app/modules/onboarding/assets/js/components/button.js
  app/modules/onboarding/assets/js/components/go-pro-popover.js
  app/modules/onboarding/assets/js/components/layout/header.js
  app/modules/onboarding/assets/js/components/layout/layout.js
  app/modules/onboarding/assets/js/components/progress-bar/progress-bar.js
  app/modules/onboarding/assets/js/components/skip-button.js
  app/modules/onboarding/assets/js/pages/account.js
  app/modules/onboarding/assets/js/pages/choose-features.js
  app/modules/onboarding/assets/js/pages/good-to-go.js
  app/modules/onboarding/assets/js/pages/hello-theme.js
  app/modules/onboarding/assets/js/utils/connect.js
  app/modules/onboarding/assets/js/utils/modules/click-tracker.js
  app/modules/onboarding/assets/js/utils/modules/event-dispatcher.js
  app/modules/onboarding/assets/js/utils/modules/onboarding-tracker.js
  app/modules/onboarding/assets/js/utils/modules/post-onboarding-tracker.js
  app/modules/onboarding/assets/js/utils/modules/storage-manager.js
  app/modules/onboarding/assets/js/utils/modules/timing-manager.js
  app/modules/onboarding/assets/js/utils/onboarding-event-tracking.js
  assets/dev/js/editor/editor-base.js
  assets/dev/js/editor/utils/post-onboarding-tracking.js
  core/common/modules/connect/apps/library.php
Labels: 🚨 1 Unresolved Thread(s), 30 min review, cp_3.32

#32846 Internal: Custom CSS > Experiment deletion [ED-20932]
  modules/atomic-widgets/module.php
  modules/atomic-widgets/styles/styles-renderer.php
  packages/packages/core/editor-canvas/src/renderers/create-styles-renderer.ts
  packages/packages/libs/editor-v1-adapters/src/readers/index.ts
Labels: 1 min review

#32896 Internal: Update connect flow [ED-21121]
  modules/pro-install/pro-install-menu-item.php
Labels: run-tests, cp_3.32

#32894 Internal: Update import export customization handling [ED-21120]
  app/modules/import-export-customization/assets/js/export/pages/export-complete.js
  app/modules/import-export-customization/assets/js/import/pages/import-complete.js
  app/modules/import-export-customization/assets/js/shared/components/kit-content-customization-dialog.js
  app/modules/import-export-customization/assets/js/shared/components/kit-plugins-customization-dialog.js
  app/modules/import-export-customization/assets/js/shared/components/kit-settings-customization-dialog.js
  app/modules/import-export-customization/assets/js/shared/utils/analytics-transformer.js
  app/modules/import-export-customization/module.php
  tests/jest/unit/app/modules/import-export-customization/assets/js/export/pages/export-complete.test.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/import/pages/import-complete.test.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/shared/components/kit-content-customization-dialog.test.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/shared/components/kit-plugins-customization-dialog.test.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/shared/utils/analytics-transformer.test.js
Labels: 30 min review, cp_3.32

#32908 Internal: Update import export customization handling [ED-21120]
  app/modules/import-export-customization/assets/js/export/pages/export-complete.js
  app/modules/import-export-customization/assets/js/import/pages/import-complete.js
  app/modules/import-export-customization/assets/js/shared/components/kit-content-customization-dialog.js
  app/modules/import-export-customization/assets/js/shared/components/kit-plugins-customization-dialog.js
  app/modules/import-export-customization/assets/js/shared/components/kit-settings-customization-dialog.js
  app/modules/import-export-customization/assets/js/shared/utils/analytics-transformer.js
  app/modules/import-export-customization/module.php
  tests/jest/unit/app/modules/import-export-customization/assets/js/export/pages/export-complete.test.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/import/pages/import-complete.test.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/shared/components/kit-content-customization-dialog.test.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/shared/components/kit-plugins-customization-dialog.test.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/shared/utils/analytics-transformer.test.js
Labels: 30 min review

#32913 Internal: Improvements to pro-install flow to 3.32 [ED-21096]
  modules/pro-install/assets/js/pro-install-events.js
  modules/pro-install/pro-install-menu-item.php
Labels: 1 min review

#32915 Internal: Bump version 3.32.3 to main
  changelog.txt
  readme.txt
Labels: 1 min review

#32888 Tweak: On export, uploading the media zip to the server [ED-20956]
  app/modules/import-export-customization/assets/js/export/hooks/use-export-kit.js
  app/modules/import-export-customization/data/routes/process-media.php
  includes/template-library/classes/class-media-collector.php
  modules/cloud-kit-library/connect/cloud-kits.php
  modules/cloud-kit-library/module.php
  tests/phpunit/elementor/app/import-export-customization/data/routes/test-process-media.php
  tests/phpunit/elementor/template-library/test-media-collector.php
Labels: 10 min review

#32917 Fix: Allow negative values in letter and word spacing [ED-21093]
  packages/packages/core/editor-editing-panel/src/components/style-sections/typography-section/letter-spacing-field.tsx
  packages/packages/core/editor-editing-panel/src/components/style-sections/typography-section/word-spacing-field.tsx
Labels: 1 min review

#32883 Internal: Typography spacing tests [ED-19720]
  packages/packages/core/editor-editing-panel/src/components/collapsible-content.tsx
  packages/packages/core/editor-editing-panel/src/components/section-content.tsx
  packages/packages/core/editor-editing-panel/src/components/section.tsx
  packages/packages/core/editor-editing-panel/src/components/styles-field-layout.tsx
  tests/playwright/drivers/driver-factory.ts
  tests/playwright/drivers/editor-driver.ts
  tests/playwright/pages/atomic-elements-panel/style-tab.ts
  tests/playwright/pages/atomic-elements-panel/v4-elements-panel.ts
  tests/playwright/pages/editor-page.ts
  tests/playwright/sanity/admin/new-templates/new-template.test.ts
  tests/playwright/sanity/modules/v4-tests/typography/typography-constants.ts
  tests/playwright/sanity/modules/v4-tests/typography/typography-test-helpers.ts
  tests/playwright/sanity/modules/v4-tests/typography/v4-typography-letter-spacing.test.ts
  tests/playwright/sanity/modules/v4-tests/typography/v4-typography-word-spacing.test.ts
  tests/playwright/utils/unit-conversions.ts
Labels: run-tests, 🚨 3 Unresolved Thread(s), 30 min review
