Repository elementor/elementor, pull requests merged in 2025-07, with the labels that each got.

#31671 Internal: Changelog for v3.30 GA
  changelog.txt
  readme.txt
Labels: 1 min review

#31672 Internal: Changelog for v3.30 to main
  changelog.txt
  readme.txt
Labels: 1 min review

#31673 Internal: Add release owner
  .github/workflows/config.json
Labels: 1 min review, missing-jira

#31635 Internal: Set initial style props conditions [ED-19637]
  modules/atomic-widgets/prop-types/base/object-prop-type.php
  modules/atomic-widgets/prop-types/union-prop-type.php
  modules/atomic-widgets/styles/style-schema.php
Labels: 1 min review, 🚨 1 Unresolved Thread(s)

#30974 Internal: Create Admin notice informing users about changes in our T&C [ED-18748]
  core/admin/admin-notices.php
  includes/tracker.php
  modules/editor-events/module.php
  tests/phpunit/elementor/includes/test-tracker.php
Labels: 10 min review, 🚨 1 Unresolved Thread(s)

#31669 Internal: IE Experiments [ED-19623]
  app/modules/import-export/runners/export/site-settings.php
  app/modules/import-export/runners/import/site-settings.php
  app/modules/import-export/runners/revert/site-settings.php
  tests/phpunit/elementor/app/import-export/processes/test-export.php
  tests/phpunit/elementor/app/import-export/processes/test-import.php
Labels: 10 min review

#31700 Internal: Fix metform plugin [ED-19866]
  tests/playwright/sanity/plugin-tester-generator.ts
Labels: run-tests, cp_3.30, cp_3.29, 1 min review

#31710 Internal: Update release owner list on main core [ED-19858]
  .github/workflows/config.json
Labels: 1 min review

#31699 Internal: Export app unit tests [ED-19803]
  app/modules/import-export-customization/assets/js/export/components/export-complete-download-link.js
  app/modules/import-export-customization/assets/js/export/components/export-complete-heading.js
  app/modules/import-export-customization/assets/js/export/components/export-complete-icon.js
  app/modules/import-export-customization/assets/js/export/components/export-complete-summary.js
  app/modules/import-export-customization/assets/js/export/components/export-error.js
  app/modules/import-export-customization/assets/js/export/components/export-kit-footer.js
  app/modules/import-export-customization/assets/js/export/pages/export-complete.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/export/components/export-error.test.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/export/components/export-kit-footer.test.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/export/context/export-context.test.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/export/hooks/use-export-kit.test.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/export/pages/export-complete.test.js
Labels: 🚨 6 Unresolved Thread(s), 30 min review

#31686 Internal: Update button ID notice on Button widget [ED-19853]
  includes/widgets/traits/button-trait.php
  tests/qunit/mock/elments/button.json
  tests/qunit/mock/elments/form.json
Labels: run-tests, 1 min review

#31715 Internal: Update the TNC date [ED-18748]
  includes/tracker.php
  modules/editor-events/module.php
Labels: 1 min review

#31716 Internal: Create Admin notice informing users about changes in our T&C [ED-18748] (#30974)
  core/admin/admin-notices.php
  includes/tracker.php
  modules/editor-events/module.php
  tests/phpunit/elementor/includes/test-tracker.php
Labels: 10 min review

#31676 Internal: Remove usage of unsecure `print_unescaped_setting()` function [ED-19758]
  includes/widgets/alert.php
  includes/widgets/counter.php
  includes/widgets/icon-box.php
  includes/widgets/testimonial.php
  includes/widgets/traits/button-trait.php
Labels: run-tests, 1 min review

#31717 Internal: Update utils version [ED-19865]
  package-lock.json
  package.json
Labels: 1 min review

#31721 Internal: Fix PW tests [ED-19665]
  tests/playwright/assets/api-requests.ts
  tests/playwright/sanity/assets/js/editor/editor.test.ts-snapshots/editor-panel-linux.jpg
  tests/playwright/sanity/modules/div-block/div-block.test.ts
Labels: run-tests, 1 min review

#31725 Internal: New Contributing.md file [ED-19665]
  CONTRIBUTING.md
  packages/CONTRIBUTING.md
Labels: 5 min review, 🗑️ Deleted files

#31726 Internal: Changelog for v3.30.1
  changelog.txt
  readme.txt
Labels: 1 min review

#31723 Internal: Export styles inheritance registry [ED-19215]
  packages/packages/core/editor-editing-panel/src/index.ts
Labels: 1 min review

#31724 Internal: Show transformed on on indications popover [ED-19215]
  packages/packages/core/editor-variables/src/init-color-variables.ts
  packages/packages/core/editor-variables/src/init-font-variables.ts
Labels: 1 min review

#31738 Internal: Hide styles fields from schema conditions [ED-19775]
  packages/packages/core/editor-editing-panel/src/components/style-sections/layout-section/__tests__/align-items-field.test.tsx
  packages/packages/core/editor-editing-panel/src/components/style-sections/layout-section/__tests__/flex-direction-field.test.tsx
  packages/packages/core/editor-editing-panel/src/components/style-sections/layout-section/__tests__/flex-order-field.test.tsx
  packages/packages/core/editor-editing-panel/src/components/style-sections/layout-section/__tests__/justify-content-field.test.tsx
  packages/packages/core/editor-editing-panel/src/components/style-sections/position-section/__tests__/dimensions-field.test.tsx
  packages/packages/core/editor-editing-panel/src/components/style-sections/position-section/__tests__/position-section.test.tsx
  packages/packages/core/editor-editing-panel/src/components/style-sections/size-section/object-position-field.tsx
  packages/packages/core/editor-editing-panel/src/components/style-sections/size-section/size-section.tsx
  packages/packages/core/editor-editing-panel/src/components/style-sections/typography-section/__tests__/font-style-field.test.tsx
  packages/packages/core/editor-editing-panel/src/components/style-sections/typography-section/typography-section.tsx
  packages/packages/core/editor-editing-panel/src/controls-registry/__tests__/styles-field-with-inheritance-indicator.test.tsx
  packages/packages/core/editor-editing-panel/src/controls-registry/__tests__/styles-field.test.tsx
  packages/packages/core/editor-editing-panel/src/controls-registry/conditional-field.tsx
  packages/packages/core/editor-editing-panel/src/controls-registry/get-dependency-state.ts
  packages/packages/core/editor-editing-panel/src/controls-registry/settings-field.tsx
  packages/packages/core/editor-editing-panel/src/controls-registry/styles-field.tsx
  packages/packages/libs/editor-props/src/index.ts
  packages/packages/libs/editor-props/src/utils/prop-dependency-utils.ts
Labels: 🗑️ Deleted files, 30 min review

#31684 Internal: Dynamic fix [ED-19546]
  modules/atomic-widgets/dynamic-tags/dynamic-prop-types-mapping.php
  modules/atomic-widgets/elements/div-block/div-block.php
  modules/atomic-widgets/prop-dependencies/manager.php
  modules/atomic-widgets/prop-types/base/array-prop-type.php
  modules/atomic-widgets/prop-types/base/object-prop-type.php
  modules/atomic-widgets/prop-types/base/plain-prop-type.php
  modules/atomic-widgets/prop-types/union-prop-type.php
  packages/packages/core/editor-editing-panel/src/controls-registry/__tests__/settings-field.test.tsx
  packages/packages/core/editor-editing-panel/src/controls-registry/settings-field.tsx
  packages/packages/core/editor-editing-panel/src/utils/prop-dependency-utils.ts
  packages/packages/libs/editor-elements/src/hooks/use-element-type.ts
  packages/packages/libs/editor-elements/src/index.ts
  packages/packages/libs/editor-elements/src/sync/get-element-setting.ts
  packages/packages/libs/editor-elements/src/sync/types.ts
  packages/packages/libs/editor-elements/src/types.ts
  packages/packages/libs/editor-props/src/index.ts
  packages/packages/libs/editor-props/src/utils/__tests__/prop-dependency-utils.test.ts
  packages/packages/libs/editor-props/src/utils/prop-dependency-utils.ts
  packages/tests/test-utils/create-mock-element.ts
  packages/tests/test-utils/create-mock-prop-type.ts
  tests/phpunit/elementor/modules/atomic-widgets/prop-dependencies/test-dependencies-manager.php
Labels: 30 min review

#31733 Tweak: Drag & Drop component [ED-19855]
  app/modules/import-export-customization/assets/js/import/components/drop-zone.js
  app/modules/import-export-customization/assets/js/import/hooks/use-drop-zone.js
  app/modules/import-export-customization/assets/js/import/utils/file-validation.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/import/components/drop-zone.test.js
Labels: 30 min review

#31743 Fix: IE app UI Theme [ED-19936]
  app/modules/import-export-customization/assets/js/export/components/kit-content.js
  app/modules/import-export-customization/assets/js/export/components/kit-info.js
  app/modules/import-export-customization/assets/js/shared/components/layout/base-layout.js
  app/modules/import-export-customization/assets/js/shared/components/layout/footer.js
  app/modules/import-export-customization/module.php
Labels: 5 min review

#31744 Fix: IE app UI Theme [ED-19936]
  app/modules/import-export-customization/assets/js/export/components/export-complete-summary.js
Labels: 1 min review

#31740 Internal: Fix elements regression failures
  package-lock.json
  package.json
  tests/playwright/sanity/assets/js/editor/editor.test.ts-snapshots/editor-panel-linux.jpg
Labels: run-tests, 1 min review

#31713 Internal: IE Customization add REST API unit tests [ED-19804]
  app/modules/import-export-customization/data/routes/base-route.php
  app/modules/import-export-customization/data/routes/export.php
  tests/phpunit/elementor/app/import-export-customization/data/routes/test-export.php
  tests/phpunit/elementor/app/import-export-customization/data/test-controller.php
  tests/phpunit/elementor/core/experiments/test-manager.php
Labels: 30 min review, 🚨 8 Unresolved Thread(s)

#31748 Fix: IE app UI Theme [ED-19936]
  app/modules/import-export-customization/assets/js/shared/components/layout/page-header.js
Labels: 1 min review

#31757 Internal: Update dependabot.yml
  .github/dependabot.yml
Labels: 1 min review

#31760 Internal: Update packages
  package-lock.json
  package.json
Labels: 1 min review

#31758 Internal: Inherit dependencies in variable union [ED-19955]
  modules/variables/classes/style-schema.php
Labels: 1 min review

#31775 Tweak: Fixed indicators for style effects
  packages/packages/core/editor-editing-panel/src/components/style-sections/effects-section/effects-section.tsx
  packages/packages/core/editor-editing-panel/src/components/style-sections/effects-section/opacity-control-field.tsx
  packages/packages/core/editor-editing-panel/src/components/style-tab.tsx
Labels: 1 min review, 🚨 1 Unresolved Thread(s)

#31778 internal: Changelog for 3.30.2 to 3.30
  changelog.txt
  readme.txt
Labels: 1 min review

#31779 Internal: Changelog 3.30.2 to main
  changelog.txt
  readme.txt
Labels: 1 min review

#31781 Revert "Internal: Create centralized place for rendering styles [ED-1…
  includes/frontend.php
  modules/atomic-widgets/cache-validity.php
  modules/atomic-widgets/memo.php
  modules/atomic-widgets/module.php
  modules/atomic-widgets/styles/atomic-styles-manager.php
  modules/atomic-widgets/styles/atomic-widget-base-styles.php
  modules/atomic-widgets/styles/atomic-widget-styles.php
  modules/atomic-widgets/styles/css-files-manager.php
  modules/atomic-widgets/styles/style-file.php
  modules/atomic-widgets/styles/styles-renderer.php
  modules/global-classes/atomic-global-styles.php
  modules/global-classes/global-classes-css-file.php
  modules/global-classes/global-classes-css-preview.php
  modules/global-classes/global-classes-css.php
  modules/global-classes/module.php
  tests/phpunit/elementor/modules/atomic-widgets/styles/test-atomic-styles-manager.php
  tests/phpunit/elementor/modules/atomic-widgets/styles/test-atomic-widget-styles.php
  tests/phpunit/elementor/modules/atomic-widgets/styles/test-atomic-widgets-base-styles.php
  tests/phpunit/elementor/modules/atomic-widgets/styles/test-css-files-manager.php
  tests/phpunit/elementor/modules/atomic-widgets/test-cache-validity.php
  tests/phpunit/elementor/modules/global-classes/test-atomic-global-styles.php
  tests/phpunit/elementor/modules/global-classes/test-global-classes-css.php
  tests/phpunit/elementor/modules/variables/atomic-widgets-styles/test-style-renderer.php
Labels: 🚨 1 Unresolved Thread(s), 🗑️ Deleted files, 30 min review

#31756 Tweak: Use CSS logical properties in Star Rating widget [ED-19953]
  assets/dev/scss/frontend/widgets/rating.scss
  includes/widgets/star-rating.php
Labels: run-tests, 1 min review

#31762 Tweak: Use CSS logical properties in Alert widget [ED-19954]
  assets/dev/scss/frontend/widgets/alert.scss
  includes/widgets/alert.php
Labels: run-tests, 1 min review

#31755 Internal: Show placeholders in Toggle button controls [ED-18491]
  packages/packages/core/editor-editing-panel/src/components/style-sections/layout-section/__tests__/display-flex.test.tsx
  packages/packages/libs/editor-controls/src/components/control-toggle-button-group.tsx
  packages/packages/libs/editor-controls/src/controls/__tests__/toggle-control.test.tsx
  packages/packages/libs/editor-controls/src/controls/toggle-control.tsx
  packages/tests/test-utils/render-control.tsx
Labels: 🚨 1 Unresolved Thread(s), 20 min review

#31765 Tweak: Use CSS logical properties in Icon Box widget [ED-19959]
  assets/dev/scss/frontend/widgets/icon-box.scss
  includes/widgets/icon-box.php
  tests/elements-regression/tests/elements-regression.test.ts-snapshots/icon-box-editor-linux.png
  tests/elements-regression/tests/elements-regression.test.ts-snapshots/icon-box-mobile-linux.png
  tests/elements-regression/tests/elements-regression.test.ts-snapshots/icon-box-mobile-published-linux.png
  tests/elements-regression/tests/elements-regression.test.ts-snapshots/icon-box-published-linux.png
  tests/elements-regression/tests/elements-regression.test.ts-snapshots/icon-box-tablet-linux.png
  tests/elements-regression/tests/elements-regression.test.ts-snapshots/icon-box-tablet-published-linux.png
Labels: run-tests, 1 min review

#31791 Internal: Add skew transform control [ED-19771]
  modules/atomic-widgets/module.php
  modules/atomic-widgets/prop-types/transform/transform-prop-type.php
  modules/atomic-widgets/prop-types/transform/transform-skew-prop-type.php
  modules/atomic-widgets/props-resolver/transformers/styles/transform-skew-transformer.php
  packages/packages/core/editor-canvas/src/init-style-transformers.ts
  packages/packages/core/editor-canvas/src/transformers/styles/transform-skew-transformer.ts
  packages/packages/libs/editor-controls/src/controls/transform-control/__tests__/transform-repeater-control.test.tsx
  packages/packages/libs/editor-controls/src/controls/transform-control/functions/__tests__/skew.test.tsx
  packages/packages/libs/editor-controls/src/controls/transform-control/functions/skew.tsx
  packages/packages/libs/editor-controls/src/controls/transform-control/transform-content.tsx
  packages/packages/libs/editor-controls/src/controls/transform-control/transform-icon.tsx
  packages/packages/libs/editor-controls/src/controls/transform-control/transform-label.tsx
  packages/packages/libs/editor-controls/src/controls/transform-control/types.ts
  packages/packages/libs/editor-controls/src/controls/transform-control/use-transform-tabs-history.tsx
  packages/packages/libs/editor-props/src/prop-types/index.ts
  packages/packages/libs/editor-props/src/prop-types/transform-prop-types/skew-transform.ts
  packages/packages/libs/editor-props/src/prop-types/transform-prop-types/transform.ts
  packages/packages/libs/editor-props/src/prop-types/transform-prop-types/types.ts
Labels: missing-jira

#31823 fake PR
  tests/playwright/sanity/modules/v4-tests/e-button-test.ts
Labels: 1 min review, missing-jira

#31812 Internal: Sanitize file upload
  includes/template-library/classes/class-import-images.php
Labels: 1 min review

#31718 Internal: [V4]: Support time units in size control [ED-19762]
  modules/atomic-widgets/prop-types/size-prop-type.php
  packages/packages/core/editor-editing-panel/src/components/style-sections/position-section/offset-field.tsx
  packages/packages/libs/editor-controls/src/components/size-control/size-input.tsx
  packages/packages/libs/editor-controls/src/controls/__tests__/size-control.test.tsx
  packages/packages/libs/editor-controls/src/controls/filter-control/drop-shadow-item-content.tsx
  packages/packages/libs/editor-controls/src/controls/filter-repeater-control.tsx
  packages/packages/libs/editor-controls/src/controls/size-control.tsx
  packages/packages/libs/editor-controls/src/controls/stroke-control.tsx
  packages/packages/libs/editor-controls/src/controls/transform-control/functions/axis-row.tsx
  packages/packages/libs/editor-controls/src/controls/transform-control/functions/rotate.tsx
  packages/packages/libs/editor-controls/src/controls/transform-control/functions/skew.tsx
  packages/packages/libs/editor-controls/src/index.ts
  packages/packages/libs/editor-controls/src/utils/size-control.ts
  packages/packages/libs/editor-props/src/prop-types/size.ts
Labels: 30 min review

#31829 Internal: Refactor css filter functions to make indicators work properly in editor [ED-19875]
  modules/atomic-widgets/prop-types/blur-filter-prop-type.php
  modules/atomic-widgets/prop-types/brightness-filter-prop-type.php
  modules/atomic-widgets/prop-types/contrast-filter-prop-type.php
  modules/atomic-widgets/prop-types/css-filter-func-prop-type.php
  modules/atomic-widgets/prop-types/filter-prop-type.php
  modules/atomic-widgets/prop-types/grayscale-filter-prop-type.php
  modules/atomic-widgets/prop-types/hue-rotate-filter-prop-type.php
  modules/atomic-widgets/prop-types/invert-filter-prop-type.php
  modules/atomic-widgets/prop-types/saturate-filter-prop-type.php
  modules/atomic-widgets/prop-types/sepia-filter-prop-type.php
  modules/atomic-widgets/props-resolver/transformers/styles/filter-transformer.php
  packages/packages/core/editor-canvas/src/__tests__/styles-prop-resolver.test.ts
  packages/packages/core/editor-canvas/src/transformers/styles/filter-transformer.ts
  packages/packages/libs/editor-controls/src/controls/__tests__/filter-repeater-control.test.tsx
  packages/packages/libs/editor-controls/src/controls/filter-control/drop-shadow-item-content.tsx
  packages/packages/libs/editor-controls/src/controls/filter-control/drop-shadow-item-label.tsx
  packages/packages/libs/editor-controls/src/controls/filter-repeater-control.tsx
  packages/packages/libs/editor-controls/src/controls/select-control.tsx
  packages/packages/libs/editor-props/src/prop-types/filter-prop-types/backdrop-filter.ts
  packages/packages/libs/editor-props/src/prop-types/filter-prop-types/blur-filter.ts
  packages/packages/libs/editor-props/src/prop-types/filter-prop-types/brightness-filter.ts
  packages/packages/libs/editor-props/src/prop-types/filter-prop-types/contrast-filter.ts
  packages/packages/libs/editor-props/src/prop-types/filter-prop-types/drop-shadow-filter.ts
  packages/packages/libs/editor-props/src/prop-types/filter-prop-types/filter.ts
  packages/packages/libs/editor-props/src/prop-types/filter-prop-types/grayscale-filter.ts
  packages/packages/libs/editor-props/src/prop-types/filter-prop-types/hue-rotate-filter.ts
  packages/packages/libs/editor-props/src/prop-types/filter-prop-types/invert-filter.ts
  packages/packages/libs/editor-props/src/prop-types/filter-prop-types/saturate-filter.ts
  packages/packages/libs/editor-props/src/prop-types/filter-prop-types/sepia-filter.ts
  packages/packages/libs/editor-props/src/prop-types/index.ts
  packages/tests/test-utils/create-mock-filter-schema.ts
  packages/tests/test-utils/mock-styles-schema.ts
Labels: 🗑️ Deleted files, 30 min review

#31825 Tweak: Optimize CSS output for Masks [ED-20001]
  includes/widgets/common-base.php
Labels: run-tests, 1 min review

#31835 Internal: Update release owners check to non-case sensitive [ED-19858]
  .github/workflows/permissions/action.yml
Labels: 1 min review

#31807 Internal: [V4] Prop dependencies - remove effect and meta from logic
  modules/atomic-widgets/dynamic-tags/dynamic-prop-types-mapping.php
  modules/atomic-widgets/elements/div-block/div-block.php
  modules/atomic-widgets/prop-dependencies/manager.php
  modules/atomic-widgets/prop-types/base/array-prop-type.php
  modules/atomic-widgets/prop-types/base/object-prop-type.php
  modules/atomic-widgets/prop-types/base/plain-prop-type.php
  modules/atomic-widgets/prop-types/contracts/prop-type.php
  modules/atomic-widgets/prop-types/link-prop-type.php
  modules/atomic-widgets/prop-types/union-prop-type.php
  modules/atomic-widgets/styles/style-schema.php
  modules/variables/classes/style-schema.php
  packages/packages/core/editor-editing-panel/src/controls-registry/__tests__/settings-field.test.tsx
  packages/packages/core/editor-editing-panel/src/controls-registry/__tests__/styles-field.test.tsx
  packages/packages/core/editor-editing-panel/src/controls-registry/conditional-field.tsx
  packages/packages/core/editor-editing-panel/src/controls-registry/get-dependency-state.ts
  packages/packages/core/editor-editing-panel/src/controls-registry/settings-field.tsx
  packages/packages/core/editor-editing-panel/src/controls-registry/styles-field.tsx
  packages/packages/core/editor-editing-panel/src/utils/prop-dependency-utils.ts
  packages/packages/libs/editor-props/src/index.ts
  packages/packages/libs/editor-props/src/types.ts
  packages/packages/libs/editor-props/src/utils/__tests__/prop-dependency-utils.test.ts
  packages/packages/libs/editor-props/src/utils/prop-dependency-utils.ts
  packages/tests/test-utils/create-mock-prop-type.ts
  tests/phpunit/elementor/modules/atomic-widgets/dynamic-tags/test-dynamic-tags-module.php
  tests/phpunit/elementor/modules/atomic-widgets/prop-dependencies/test-dependencies-manager.php
  tests/phpunit/elementor/modules/atomic-widgets/utils/mock-array-prop-type.php
  tests/phpunit/elementor/modules/atomic-widgets/utils/mock-object-prop-type.php
  tests/phpunit/elementor/modules/atomic-widgets/utils/mock-prop-type.php
Labels: 🚨 6 Unresolved Thread(s), 🗑️ Deleted files, 30 min review

#31843 Internal: Validate dry run really a dry run [ED-20017]
  .github/workflows/one-click-release.yml
  .github/workflows/release-dev-from-beta/action.yml
Labels: 1 min review

#31851 Fix: Issues with build creation breaks the V4 Attributes feature[ED-19956]
  php-scoper/twig-inc.php
Labels: 1 min review

#31844 Internal: Prevent the indications popover from opening in the Repeaters controls [ED-20023]
  packages/packages/core/editor-editing-panel/src/styles-inheritance/components/styles-inheritance-indicator.tsx
Labels: 1 min review, 🚨 3 Unresolved Thread(s)

#31854 Internal: Fix build script [ED-19956]
  package.json
Labels: 1 min review, 🚨 1 Unresolved Thread(s)

#31852 Internal: Fix CI build plugin flow [ED-19956]
  .github/scripts/build-zip.sh
  .github/workflows/build.yml
  .github/workflows/install-dependencies/action.yml
Labels: run-tests, 1 min review

#31800 Internal: Show placeholders in SizeControl [ED-19244]
  packages/packages/libs/editor-controls/src/components/size-control/text-field-inner-selection.tsx
  packages/packages/libs/editor-controls/src/controls/__tests__/size-control.test.tsx
  packages/packages/libs/editor-controls/src/controls/size-control.tsx
  packages/packages/libs/editor-controls/src/utils/size-control.ts
Labels: 20 min review

#31876 Internal: Write build comment error fix [ED-20070]
  .github/workflows/build.yml
Labels: 1 min review

#31908 Internal: Add controlled state to control floating actions bar [ED-19…
  package-lock.json
  package.json
  packages/package-lock.json
  packages/packages/core/editor-app-bar/package.json
  packages/packages/core/editor-canvas/package.json
  packages/packages/core/editor-editing-panel/package.json
  packages/packages/core/editor-editing-panel/src/__tests__/popover-action.test.tsx
  packages/packages/core/editor-editing-panel/src/controls-actions.ts
  packages/packages/core/editor-editing-panel/src/popover-action.tsx
  packages/packages/core/editor-global-classes/package.json
  packages/packages/core/editor-notifications/package.json
  packages/packages/core/editor-panels/package.json
  packages/packages/core/editor-site-navigation/package.json
  packages/packages/core/editor-variables/package.json
  packages/packages/core/editor/package.json
  packages/packages/libs/editor-controls/package.json
  packages/packages/libs/editor-controls/src/components/floating-bar.tsx
  packages/packages/libs/editor-controls/src/control-actions/control-actions.tsx
  packages/packages/libs/editor-controls/src/index.ts
  packages/packages/libs/editor-ui/package.json
Labels: 20 min review

#31903 Internal: Merge 3.30-3.31 experiments into V4 [ED-20081]
  modules/atomic-widgets/module.php
  modules/atomic-widgets/parsers/style-parser.php
  modules/global-classes/global-classes-parser.php
  packages/packages/core/editor-canvas/src/__tests__/styles-prop-resolver.test.ts
  packages/packages/core/editor-canvas/src/transformers/styles/background-overlay-transformer.ts
  packages/packages/core/editor-editing-panel/src/__tests__/reset-style-value-props.test.ts
  packages/packages/core/editor-editing-panel/src/components/__tests__/settings-tab.test.tsx
  packages/packages/core/editor-editing-panel/src/components/css-classes/__tests__/css-class-selector.test.tsx
  packages/packages/core/editor-editing-panel/src/components/css-classes/use-apply-and-unapply-class.ts
  packages/packages/core/editor-editing-panel/src/components/editing-panel-tabs.tsx
  packages/packages/core/editor-editing-panel/src/components/section.tsx
  packages/packages/core/editor-editing-panel/src/components/settings-tab.tsx
  packages/packages/core/editor-editing-panel/src/components/style-sections/effects-section/effects-section.tsx
  packages/packages/core/editor-editing-panel/src/components/style-sections/layout-section/__tests__/display-flex.test.tsx
  packages/packages/core/editor-editing-panel/src/components/style-sections/layout-section/display-field.tsx
  packages/packages/core/editor-editing-panel/src/components/style-sections/position-section/position-section.tsx
  packages/packages/core/editor-editing-panel/src/components/style-sections/size-section/__tests__/size-section.test.tsx
  packages/packages/core/editor-editing-panel/src/components/style-sections/size-section/size-section.tsx
  packages/packages/core/editor-editing-panel/src/components/style-sections/typography-section/typography-section.tsx
  packages/packages/core/editor-editing-panel/src/components/style-tab-collapsible-content.tsx
  packages/packages/core/editor-editing-panel/src/components/style-tab-section.tsx
  packages/packages/core/editor-editing-panel/src/controls-registry/__tests__/settings-field.test.tsx
  packages/packages/core/editor-editing-panel/src/controls-registry/settings-field.tsx
  packages/packages/core/editor-editing-panel/src/controls-registry/styles-field.tsx
  packages/packages/core/editor-editing-panel/src/hooks/__tests__/use-styles-fields.test.ts
  packages/packages/core/editor-editing-panel/src/hooks/use-state-by-element.ts
  packages/packages/core/editor-editing-panel/src/hooks/use-styles-fields.ts
  packages/packages/core/editor-editing-panel/src/index.ts
  packages/packages/core/editor-editing-panel/src/init.ts
  packages/packages/core/editor-editing-panel/src/styles-inheritance/components/styles-inheritance-indicator.tsx
  packages/packages/core/editor-editing-panel/src/styles-inheritance/consts.ts
  packages/packages/core/editor-editing-panel/src/styles-inheritance/init.ts
  packages/packages/core/editor-editing-panel/src/sync/experiments-flags.ts
  packages/packages/core/editor-global-classes/src/components/class-manager/__tests__/class-manager-panel.test.tsx
  packages/packages/core/editor-global-classes/src/components/class-manager/class-item.tsx
  packages/packages/core/editor-global-classes/src/components/class-manager/class-manager-panel.tsx
  packages/packages/core/editor-global-classes/src/global-classes-styles-provider.ts
  packages/packages/libs/editor-controls/src/controls/background-control/background-control.tsx
  packages/packages/libs/editor-controls/src/controls/equal-unequal-sizes-control.tsx
  packages/packages/libs/editor-controls/src/controls/link-control.tsx
  packages/packages/libs/editor-controls/src/controls/linked-dimensions-control.tsx
  packages/packages/libs/editor-controls/src/controls/position-control.tsx
  packages/packages/libs/editor-controls/src/hooks/use-size-extended-options.ts
  packages/packages/libs/editor-ui/src/components/popover/header.tsx
  packages/packages/libs/editor-ui/src/components/popover/menu-list.tsx
  packages/packages/libs/editor-ui/src/components/popover/search.tsx
  tests/playwright/sanity/modules/v4-tests/atomic-widgets.test.ts
  tests/playwright/sanity/modules/v4-tests/e-button-test.ts
  tests/playwright/sanity/modules/v4-tests/link-control.test.ts
Labels: 🚨 1 Unresolved Thread(s), 20 min review, 🗑️ Deleted files

#31914 Internal: Class usage count locator [ED-19152]
  modules/global-classes/global-classes-rest-api.php
  modules/global-classes/usage/applied-global-classes-usage.php
  modules/global-classes/usage/css-class-usage.php
  modules/global-classes/usage/document-usage.php
  modules/global-classes/usage/global-classes-usage.php
  packages/packages/core/editor-documents/src/hooks/__tests__/use-open-document-in-new-tab.test.ts
  packages/packages/core/editor-documents/src/hooks/index.ts
  packages/packages/core/editor-documents/src/hooks/use-navigate-to-document.ts
  packages/packages/core/editor-documents/src/hooks/use-open-document-in-new-tab.ts
  packages/packages/core/editor-documents/src/hooks/utils.ts
  packages/packages/core/editor-documents/src/index.ts
  packages/packages/core/editor-global-classes/service/css-class-usage-service.ts
  packages/packages/core/editor-global-classes/src/api.ts
  packages/packages/core/editor-global-classes/src/components/class-manager/__tests__/class-manager-button.test.tsx
  packages/packages/core/editor-global-classes/src/components/class-manager/__tests__/global-classes-list.test.tsx
  packages/packages/core/editor-global-classes/src/components/class-manager/class-item.tsx
  packages/packages/core/editor-global-classes/src/components/class-manager/class-manager-button.tsx
  packages/packages/core/editor-global-classes/src/components/class-manager/class-manager-panel.tsx
  packages/packages/core/editor-global-classes/src/components/class-manager/delete-confirmation-dialog.tsx
  packages/packages/core/editor-global-classes/src/components/css-class-usage/__tests__/css-class-usage-popover.test.tsx
  packages/packages/core/editor-global-classes/src/components/css-class-usage/__tests__/css-class-usage-service.test.tsx
  packages/packages/core/editor-global-classes/src/components/css-class-usage/__tests__/css-class-usage-trigger.test.tsx
  packages/packages/core/editor-global-classes/src/components/css-class-usage/__tests__/use-css-class-usage-by-id.test.tsx
  packages/packages/core/editor-global-classes/src/components/css-class-usage/components/css-class-usage-popover.tsx
  packages/packages/core/editor-global-classes/src/components/css-class-usage/components/css-class-usage-trigger.tsx
  packages/packages/core/editor-global-classes/src/components/css-class-usage/components/index.ts
  packages/packages/core/editor-global-classes/src/components/css-class-usage/types.ts
  packages/packages/core/editor-global-classes/src/components/css-class-usage/utils.ts
  packages/packages/core/editor-global-classes/src/hooks/use-css-class-usage-by-id.ts
  packages/packages/core/editor-global-classes/src/hooks/use-css-class-usage.ts
  packages/packages/core/editor-global-classes/src/hooks/use-prefetch-css-class-usage.ts
  packages/packages/libs/editor-ui/src/components/popover/header.tsx
  tests/phpunit/elementor/modules/global-classes/test-css-class-usage.php
  tests/phpunit/elementor/modules/global-classes/test-global-classes-rest-api.php
  tests/phpunit/elementor/modules/global-classes/test-global-classes-usage.php
Labels: 🚨 2 Unresolved Thread(s), 🗑️ Deleted files, 30 min review

#31922 Internal: Close revert PRs if not merged [ED-20106]
  .github/workflows/cleanup-revert-prs.yml
Labels: 1 min review, 🚨 3 Unresolved Thread(s)

#31929 Internal: Remove usage of unsecure `print_unescaped_setting()` function [ED-19758]
  includes/widgets/alert.php
  includes/widgets/counter.php
  includes/widgets/icon-box.php
  includes/widgets/testimonial.php
  includes/widgets/traits/button-trait.php
Labels: 1 min review, 🚨 2 Unresolved Thread(s)

#31937 Revert "Internal: Issues write permissions in the build"
  .github/workflows/build.yml
Labels: 1 min review, 🚨 1 Unresolved Thread(s)

#31932 Internal: Promotion for Send - related to Forms [ED-20113]
  core/admin/admin-notices.php
Labels: 10 min review, 🚨 1 Unresolved Thread(s)

#31939 Internal: Revert "Optimized Markup" activation for all websites [ED-20115]
  core/experiments/manager.php
Labels: 1 min review, 🚨 2 Unresolved Thread(s)

#31933 Tweak: Keep the placeholder unit on size control [ED-20062]
  packages/packages/libs/editor-controls/src/controls/__tests__/size-control.test.tsx
  packages/packages/libs/editor-controls/src/controls/size-control.tsx
Labels: 1 min review, 🚨 1 Unresolved Thread(s)

#31941 Internal: [V4] Variables - Trigger Edit variable alert [ED-20058]
  packages/packages/core/editor-variables/src/components/color-variable-edit.tsx
  packages/packages/core/editor-variables/src/components/font-variable-edit.tsx
  packages/packages/core/editor-variables/src/components/ui/edit-confirmation-dialog.tsx
Labels: 10 min review, 🚨 8 Unresolved Thread(s)

#31930 Internal: Export content customization [ED-19806]
  app/modules/import-export-customization/assets/js/shared/components/customization-list-setting-section.js
  app/modules/import-export-customization/assets/js/shared/components/customization-setting-section.js
  app/modules/import-export-customization/assets/js/shared/components/customization-sub-setting.js
  app/modules/import-export-customization/assets/js/shared/components/kit-content-customization-dialog.js
  app/modules/import-export-customization/assets/js/shared/components/kit-customization-dialog.js
  app/modules/import-export-customization/assets/js/shared/components/kit-settings-customization-dialog.js
  app/modules/import-export-customization/assets/js/shared/hooks/use-custom-post-types.js
  app/modules/import-export-customization/assets/js/shared/hooks/use-pages.js
  app/modules/import-export-customization/assets/js/shared/hooks/use-taxonomies.js
  app/modules/import-export-customization/assets/js/shared/kit-content-data.js
  app/modules/import-export-customization/processes/export.php
  app/modules/import-export-customization/runners/export/elementor-content.php
  app/modules/import-export-customization/runners/export/taxonomies.php
  app/modules/import-export-customization/runners/export/wp-content.php
  app/modules/import-export-customization/utils.php
  core/utils/import-export/wp-exporter.php
  tests/jest/unit/app/modules/import-export-customization/assets/js/components/customization-list-setting-section.test.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/components/customization-setting-section.test.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/components/customization-sub-setting.test.js
Labels: 🚨 2 Unresolved Thread(s), 30 min review

#31952 Tweak: Implement templates customization to the export process [ED-19807]
  app/modules/import-export-customization/assets/js/shared/components/kit-customization-dialog.js
  app/modules/import-export-customization/assets/js/shared/components/kit-templates-customization-dialog.js
  app/modules/import-export-customization/assets/js/shared/kit-content-data.js
  app/modules/import-export-customization/runners/export/templates.php
  modules/library/documents/library-document.php
  tests/jest/unit/app/modules/import-export-customization/assets/js/shared/components/kit-templates-customization-dialog.test.js
Labels: 🚨 1 Unresolved Thread(s), 30 min review

#31955 Internal: Remove of unused scripts and workflows
  .github/scripts/add-to-readme-beta-tag.sh
  .github/scripts/build-wp-env.js
  .github/scripts/changelog-generator-v2.js
  .github/scripts/commit-push-bump.sh
  .github/scripts/fetch-merged-prs.sh
  .github/scripts/get-beta-version.js
  .github/scripts/get-changelog-from-readme-txt.js
  .github/scripts/get-release-branch-name.sh
  .github/scripts/get-release-date.sh
  .github/scripts/publish-readme-to-wordpress-org.sh
  .github/scripts/remove-readme-beta-tag.sh
  .github/scripts/repo-utils.js
  .github/scripts/screenshotter-cleanup.js
  .github/scripts/set-git-user.sh
  .github/scripts/slack-notify.sh
  .github/scripts/update-readme-stable-version.sh
  .github/scripts/update-version-elementor-php.sh
  .github/workflows/copy-file/action.yml
  .github/workflows/create-git-tag/action.yml
  .github/workflows/get-changelog-datetime/action.yml
  .github/workflows/push-new-version/action.yml
  .github/workflows/slack-notify/action.yml
Labels: 5 min review, 🗑️ Deleted files

#31867 Internal: Fix Dynamic tag floating button location in attributes fields [ED-20026]
  packages/packages/libs/editor-controls/src/controls/key-value-control.tsx
Labels: 1 min review

#31968 Fix: Div block handles should flip when first element in page [ED-19543]
  modules/atomic-widgets/assets/js/editor/div-block-view.js
Labels: 1 min review, 🚨 2 Unresolved Thread(s)

#31971 Internal: Improve branch name and PR title [ED-20161]
  .github/workflows/cherry-pick-pr.yml
Labels: cp_3.31

#31973 Internal: Just testing [ED-20161]
  tests/playwright/sanity/modules/div-block/div-block.test.ts
Labels: cp_3.30, 1 min review

#31976 Internal: Sanitize branch name and title [ED-20161]
  tests/playwright/sanity/modules/div-block/div-block.test.ts
Labels: cp_3.31

#31980 Internal: Improve branch name and PR title for CP PRs [ED-20161]
  .github/workflows/cherry-pick-pr.yml
Labels: 1 min review, 🚨 2 Unresolved Thread(s)

#31996 Internal: [V4] Revert common controls [ED-20033]
  modules/atomic-widgets/elements/atomic-button/atomic-button.php
  modules/atomic-widgets/elements/atomic-divider/atomic-divider.php
  modules/atomic-widgets/elements/atomic-heading/atomic-heading.php
  modules/atomic-widgets/elements/atomic-image/atomic-image.php
  modules/atomic-widgets/elements/atomic-paragraph/atomic-paragraph.php
  modules/atomic-widgets/elements/atomic-svg/atomic-svg.php
  modules/atomic-widgets/elements/atomic-youtube/atomic-youtube.php
  modules/atomic-widgets/elements/div-block/div-block.php
  modules/atomic-widgets/elements/has-atomic-base.php
  tests/phpunit/elementor/modules/atomic-widgets/test-atomic-widget-base.php
Labels: run-tests

#31997 Internal: Refactor control registry to singleton
  packages/packages/core/editor-editing-panel/src/components/settings-tab.tsx
  packages/packages/core/editor-editing-panel/src/controls-registry/__tests__/control.test.tsx
  packages/packages/core/editor-editing-panel/src/controls-registry/__tests__/controls-registry.test.tsx
  packages/packages/core/editor-editing-panel/src/controls-registry/control.tsx
  packages/packages/core/editor-editing-panel/src/controls-registry/controls-registry.tsx
  packages/packages/core/editor-editing-panel/src/dynamics/components/dynamic-selection-control.tsx
  packages/packages/core/editor-editing-panel/src/errors.ts
Labels: 20 min review

#31965 Internal: Convert local class to global class [ED-20110]
  packages/packages/core/editor-editing-panel/src/components/css-classes/__tests__/css-class-selector.test.tsx
  packages/packages/core/editor-editing-panel/src/components/css-classes/css-class-convert-local.tsx
  packages/packages/core/editor-editing-panel/src/components/css-classes/css-class-item.tsx
  packages/packages/core/editor-editing-panel/src/components/css-classes/css-class-menu.tsx
  packages/packages/core/editor-editing-panel/src/components/css-classes/use-can-convert-local-class-to-global.ts
  packages/packages/core/editor-editing-panel/src/index.ts
  packages/packages/core/editor-global-classes/src/components/convert-local-class-to-global-class.tsx
  packages/packages/core/editor-global-classes/src/global-classes-styles-provider.ts
  packages/packages/core/editor-global-classes/src/init.ts
  packages/packages/core/editor-styles-repository/src/types.ts
Labels: 🚨 1 Unresolved Thread(s), 20 min review

#32003 Fix: Visual issue with key-value dynamic tag
  packages/packages/libs/editor-controls/src/controls/key-value-control.tsx
Labels: 1 min review, 🚨 1 Unresolved Thread(s)

#32000 Internal: Some scripts changes [ED-20051]
  .grunt-config/copy.js
  .grunt-config/sass.js
  package-lock.json
  package.json
Labels: 1 min review

#32006 Fix: Color for repeatable control labels [ED-20090]
  packages/packages/libs/editor-controls/src/controls/__tests__/repeatable-control.test.tsx
  packages/packages/libs/editor-controls/src/controls/repeatable-control.tsx
Labels: 1 min review

#32016 Fix: When the attribute value is longer than one word, it breaks [ED -20187]
  modules/atomic-widgets/elements/atomic-button/atomic-button.html.twig
  modules/atomic-widgets/elements/atomic-divider/atomic-divider.html.twig
  modules/atomic-widgets/elements/atomic-heading/atomic-heading.html.twig
  modules/atomic-widgets/elements/atomic-image/atomic-image.html.twig
  modules/atomic-widgets/elements/atomic-paragraph/atomic-paragraph.html.twig
  modules/atomic-widgets/elements/atomic-youtube/atomic-youtube.html.twig
  modules/atomic-widgets/elements/div-block/div-block.php
  modules/atomic-widgets/props-resolver/transformers/settings/attributes-transformer.php
Labels: 1 min review, missing-jira

#31988 Internal: Register color and font variable types [ED-20169]
  packages/packages/core/editor-variables/src/components/__tests__/color-variable-edit.test.tsx
  packages/packages/core/editor-variables/src/components/__tests__/validations.test.tsx
  packages/packages/core/editor-variables/src/components/__tests__/variable-edit.test.tsx
  packages/packages/core/editor-variables/src/components/__tests__/variable-restore.test.tsx
  packages/packages/core/editor-variables/src/components/color-variable-creation.tsx
  packages/packages/core/editor-variables/src/components/color-variable-edit.tsx
  packages/packages/core/editor-variables/src/components/color-variables-selection.tsx
  packages/packages/core/editor-variables/src/components/fields/color-field.tsx
  packages/packages/core/editor-variables/src/components/fields/font-field.tsx
  packages/packages/core/editor-variables/src/components/font-variable-restore.tsx
  packages/packages/core/editor-variables/src/components/ui/variable/assigned-variable.tsx
  packages/packages/core/editor-variables/src/components/ui/variable/deleted-variable.tsx
  packages/packages/core/editor-variables/src/components/variable-creation.tsx
  packages/packages/core/editor-variables/src/components/variable-edit.tsx
  packages/packages/core/editor-variables/src/components/variable-restore.tsx
  packages/packages/core/editor-variables/src/components/variable-selection-popover.tsx
  packages/packages/core/editor-variables/src/components/variables-selection.tsx
  packages/packages/core/editor-variables/src/context/variable-selection-popover.context.tsx
  packages/packages/core/editor-variables/src/context/variable-type-context.tsx
  packages/packages/core/editor-variables/src/controls/__tests__/color-variable-control.test.tsx
  packages/packages/core/editor-variables/src/controls/__tests__/variable-control.test.tsx
  packages/packages/core/editor-variables/src/controls/color-variable-control.tsx
  packages/packages/core/editor-variables/src/controls/font-variable-control.tsx
  packages/packages/core/editor-variables/src/controls/variable-control.tsx
  packages/packages/core/editor-variables/src/hooks/__tests__/use-prop-variable-action.test.tsx
  packages/packages/core/editor-variables/src/hooks/use-prop-color-variable-action.tsx
  packages/packages/core/editor-variables/src/hooks/use-prop-font-variable-action.tsx
  packages/packages/core/editor-variables/src/hooks/use-prop-variable-action.tsx
  packages/packages/core/editor-variables/src/index.ts
  packages/packages/core/editor-variables/src/init-color-variables.ts
  packages/packages/core/editor-variables/src/init-font-variables.ts
  packages/packages/core/editor-variables/src/init.ts
  packages/packages/core/editor-variables/src/register-variable-types.tsx
  packages/packages/core/editor-variables/src/repeater-injections.ts
  packages/packages/core/editor-variables/src/utils.ts
  packages/packages/core/editor-variables/src/variables-registry/create-variable-type-registry.ts
  packages/packages/core/editor-variables/src/variables-registry/variable-type-registry.ts
Labels: 🗑️ Deleted files, 30 min review

#31982 Internal: Create variable type registry [ED-20169]
  packages/packages/core/editor-variables/src/components/__tests__/color-variable-edit.test.tsx
  packages/packages/core/editor-variables/src/components/__tests__/validations.test.tsx
  packages/packages/core/editor-variables/src/components/__tests__/variable-edit.test.tsx
  packages/packages/core/editor-variables/src/components/__tests__/variable-restore.test.tsx
  packages/packages/core/editor-variables/src/components/color-variable-creation.tsx
  packages/packages/core/editor-variables/src/components/color-variable-edit.tsx
  packages/packages/core/editor-variables/src/components/color-variables-selection.tsx
  packages/packages/core/editor-variables/src/components/fields/color-field.tsx
  packages/packages/core/editor-variables/src/components/fields/font-field.tsx
  packages/packages/core/editor-variables/src/components/font-variable-restore.tsx
  packages/packages/core/editor-variables/src/components/ui/variable/assigned-variable.tsx
  packages/packages/core/editor-variables/src/components/ui/variable/deleted-variable.tsx
  packages/packages/core/editor-variables/src/components/variable-creation.tsx
  packages/packages/core/editor-variables/src/components/variable-edit.tsx
  packages/packages/core/editor-variables/src/components/variable-restore.tsx
  packages/packages/core/editor-variables/src/components/variable-selection-popover.tsx
  packages/packages/core/editor-variables/src/components/variables-selection.tsx
  packages/packages/core/editor-variables/src/context/variable-selection-popover.context.tsx
  packages/packages/core/editor-variables/src/context/variable-type-context.tsx
  packages/packages/core/editor-variables/src/controls/__tests__/color-variable-control.test.tsx
  packages/packages/core/editor-variables/src/controls/__tests__/variable-control.test.tsx
  packages/packages/core/editor-variables/src/controls/color-variable-control.tsx
  packages/packages/core/editor-variables/src/controls/font-variable-control.tsx
  packages/packages/core/editor-variables/src/controls/variable-control.tsx
  packages/packages/core/editor-variables/src/hooks/__tests__/use-prop-variable-action.test.tsx
  packages/packages/core/editor-variables/src/hooks/use-prop-color-variable-action.tsx
  packages/packages/core/editor-variables/src/hooks/use-prop-font-variable-action.tsx
  packages/packages/core/editor-variables/src/hooks/use-prop-variable-action.tsx
  packages/packages/core/editor-variables/src/index.ts
  packages/packages/core/editor-variables/src/init-color-variables.ts
  packages/packages/core/editor-variables/src/init-font-variables.ts
  packages/packages/core/editor-variables/src/init.ts
  packages/packages/core/editor-variables/src/register-variable-types.tsx
  packages/packages/core/editor-variables/src/repeater-injections.ts
  packages/packages/core/editor-variables/src/utils.ts
  packages/packages/core/editor-variables/src/variables-registry/__tests__/create-variable-type-registry.test.tsx
  packages/packages/core/editor-variables/src/variables-registry/create-variable-type-registry.ts
  packages/packages/core/editor-variables/src/variables-registry/variable-type-registry.ts
Labels: 🗑️ Deleted files, 30 min review

#32017 Internal: Simplify the installation of the test environment [ED-20209]
  package.json
  scripts/setup-test-environment.sh
  tests/test-environment-setup.md
  tests/wp-env/config/setup.sh
Labels: 🚨 2 Unresolved Thread(s), 20 min review

#32008 Internal: [V4] Leftover size prop fixes [ED-19513]
  modules/atomic-widgets/prop-types/background-image-overlay-size-scale-prop-type.php
  modules/atomic-widgets/prop-types/dimensions-prop-type.php
  packages/packages/libs/editor-controls/src/controls/linked-dimensions-control.tsx
  tests/phpunit/elementor/modules/atomic-widgets/styles/test-styles-renderer.php
Labels: run-tests, 1 min review

#32009 Tweak: Add plugins customization to the import process [ED-20043]
  app/modules/import-export-customization/assets/js/export/components/export-complete-summary.js
  app/modules/import-export-customization/assets/js/export/components/export-error.js
  app/modules/import-export-customization/assets/js/export/components/export-kit-footer.js
  app/modules/import-export-customization/assets/js/export/components/summary-section.js
  app/modules/import-export-customization/assets/js/export/context/export-context.js
  app/modules/import-export-customization/assets/js/export/hooks/use-export-kit.js
  app/modules/import-export-customization/assets/js/export/pages/export-complete.js
  app/modules/import-export-customization/assets/js/export/pages/export-kit.js
  app/modules/import-export-customization/assets/js/import/components/import-kit-parts-selection.js
  app/modules/import-export-customization/assets/js/import/components/plugin-activation.js
  app/modules/import-export-customization/assets/js/import/context/import-context.js
  app/modules/import-export-customization/assets/js/import/hooks/use-import-kit.js
  app/modules/import-export-customization/assets/js/import/pages/import-complete.js
  app/modules/import-export-customization/assets/js/import/pages/import-process.js
  app/modules/import-export-customization/assets/js/shared/components/kit-plugins-customization-dialog.js
  app/modules/import-export-customization/assets/js/shared/hooks/use-kit-plugins.js
  app/modules/import-export-customization/data/routes/export.php
  app/modules/import-export-customization/data/routes/import.php
  app/modules/import-export-customization/processes/export.php
  app/modules/import-export-customization/processes/import.php
  app/modules/import-export-customization/runners/export/plugins.php
  app/modules/import-export-customization/runners/import/plugins.php
  tests/jest/unit/app/modules/import-export-customization/assets/js/export/components/export-error.test.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/export/components/export-kit-footer.test.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/export/hooks/use-export-kit.test.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/export/pages/export-complete.test.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/import/hooks/use-import-kit.test.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/import/pages/import-complete.test.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/import/pages/import-process.test.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/shared/components/kit-plugins-customization-dialog.test.js
Labels: 🚨 6 Unresolved Thread(s), 30 min review

#32035 Internal: Filter sort by usage status used unused fix [ED-19153]
  packages/packages/core/editor-global-classes/src/components/search-and-filter/components/filter/clear-icon-button.tsx
  packages/packages/core/editor-global-classes/src/components/search-and-filter/components/filter/css-class-filter.tsx
  packages/packages/core/editor-global-classes/src/components/search-and-filter/components/filter/filter-list.tsx
Labels: 1 min review

#32057 Internal: [V4] Expose transition properties list for extension and use in pro. [ED-19783]
  packages/packages/libs/editor-controls/src/controls/transition-control/data.ts
  packages/packages/libs/editor-controls/src/index.ts
Labels: 1 min review

#32043 Tweak: Remove icons from the accessibility tree in Social Icons widget [ED-20230]
  includes/widgets/social-icons.php
Labels: run-tests, 1 min review

#32064 Internal: Changelog for v3.30.4
  changelog.txt
  readme.txt
Labels: 1 min review, cp_3.31, cp_main

#32066 Internal: Changelog for v3.30.4
  changelog.txt
  readme.txt
Labels: 1 min review, cp_3.31

#32067 Internal: Angie creates Pro elements to non connected pro users [AI-3856]
  modules/promotions/widgets/pro-widget-promotion.php
Labels: run-tests, 1 min review

#32073 Internal: Marketing changes to onboarding first page [ED-20203]
  app/modules/onboarding/assets/js/pages/account.js
Labels: 1 min review

#32075 Internal: Align packages version [ED-19666]
  .github/workflows/publish-packages.yml
  packages/packages/core/editor-app-bar/package.json
  packages/packages/core/editor-canvas/package.json
  packages/packages/core/editor-documents/package.json
  packages/packages/core/editor-editing-panel/package.json
  packages/packages/core/editor-global-classes/package.json
  packages/packages/core/editor-notifications/package.json
  packages/packages/core/editor-panels/package.json
  packages/packages/core/editor-site-navigation/package.json
  packages/packages/core/editor-styles-repository/package.json
  packages/packages/core/editor-variables/package.json
  packages/packages/core/editor/package.json
  packages/packages/core/frontend-handlers/package.json
  packages/packages/libs/editor-controls/package.json
  packages/packages/libs/editor-current-user/package.json
  packages/packages/libs/editor-elements/package.json
  packages/packages/libs/editor-props/package.json
  packages/packages/libs/editor-responsive/package.json
  packages/packages/libs/editor-styles/package.json
  packages/packages/libs/editor-ui/package.json
  packages/packages/libs/editor-v1-adapters/package.json
  packages/packages/libs/env/package.json
  packages/packages/libs/http-client/package.json
  packages/packages/libs/locations/package.json
  packages/packages/libs/menus/package.json
  packages/packages/libs/query/package.json
  packages/packages/libs/schema/package.json
  packages/packages/libs/session/package.json
  packages/packages/libs/store/package.json
  packages/packages/libs/twing/package.json
  packages/packages/libs/utils/package.json
  packages/packages/libs/wp-media/package.json
  packages/packages/tools/commitlint-plugin-editor/package.json
  packages/packages/tools/entry-initialization-webpack-plugin/package.json
  packages/packages/tools/eslint-plugin-editor/package.json
  packages/packages/tools/externalize-wordpress-assets-webpack-plugin/package.json
  packages/packages/tools/extract-i18n-wordpress-expressions-webpack-plugin/package.json
  packages/packages/tools/generate-wordpress-asset-file-webpack-plugin/package.json
Labels: 20 min review

#32081 Internal: Token usage in publish [ED-19666]
  .github/workflows/one-click-release.yml
  .github/workflows/publish-packages.yml
Labels: 1 min review
