Repository elementor/elementor, pull requests merged in 2025-08, with the labels that each got.

#32063 Internal: Create Variables Manager Button and structure [ED-19861]
  modules/variables/module.php
  packages/packages/core/editor-variables/package.json
  packages/packages/core/editor-variables/src/components/variable-selection-popover.tsx
  packages/packages/core/editor-variables/src/components/variables-manager/variables-manager-panel.tsx
  packages/packages/core/editor-variables/src/init.ts
Labels: 🚨 2 Unresolved Thread(s), 20 min review

#32096 Internal: Trigger packages npm publish
  packages/packages/core/editor-variables/src/hooks/__tests__/use-prop-variable-action.test.tsx
Labels: 1 min review, missing-jira

#32093 Fix: Respect reduced motion preferences in entrance/exit Animations [ED-20284]
  assets/dev/scss/frontend/_animate.scss
Labels: run-tests, 1 min review

#32080 Internal: Update top menu with connect link [ED-20191]
  core/editor/loader/common/editor-common-scripts-settings.php
  packages/packages/core/editor-app-bar/src/components/actions/link.tsx
  packages/packages/core/editor-app-bar/src/components/ui/popover-menu-item.tsx
  packages/packages/core/editor-app-bar/src/extensions/connect/hooks/use-connect-link-config.tsx
  packages/packages/core/editor-app-bar/src/extensions/connect/index.ts
  packages/packages/core/editor-app-bar/src/extensions/help/index.ts
  packages/packages/core/editor-app-bar/src/extensions/index.ts
  packages/packages/core/editor-app-bar/src/extensions/wordpress/index.ts
  packages/packages/core/editor-app-bar/src/types.ts
Labels: 🚨 5 Unresolved Thread(s), 5 min review

#32129 Internal: Make publish packages work
  .github/workflows/one-click-release.yml
  .github/workflows/publish-packages.yml
  packages/scripts/version-manager/publishing.js
Labels: 1 min review

#32125 Internal: Use Logical Properties in Elementor Import Export [ED-20303]
  app/modules/import-export/assets/js/pages/export/export-kit/export-kit.scss
  app/modules/import-export/assets/js/ui/wizard-step/wizard-step.scss
Labels: run-tests, 1 min review, 🚨 1 Unresolved Thread(s)

#32124 Internal: Use Logical Properties in Elementor Preview [ED-20302]
  assets/dev/scss/editor/preview/_column.scss
  assets/dev/scss/editor/preview/_container.scss
  assets/dev/scss/editor/preview/_inline-editor.scss
Labels: run-tests, 1 min review

#32128 Internal: Add Mixpanel events to cloud kit [ED-20046]
  core/common/app.php
Labels: run-pro-tests, run-tests, 1 min review

#32111 Internal: Add user data endpoint [ED-20296]
  includes/autoloader.php
  includes/plugin.php
  includes/user-data.php
  packages/packages/libs/editor-current-user/src/api.ts
  tests/phpunit/elementor/includes/test-user-data.php
Labels: 30 min review, 🚨 12 Unresolved Thread(s)

#32140 Revert "Internal: Add user data endpoint [ED-20296]"
  includes/autoloader.php
  includes/plugin.php
  includes/user-data.php
  packages/packages/libs/editor-current-user/src/api.ts
  tests/phpunit/elementor/includes/test-user-data.php
Labels: 5 min review, 🗑️ Deleted files

#32015 Internal: Add atomic components' styles to relevant posts [ED-20200]
  modules/atomic-widgets/cache-validity.php
  modules/atomic-widgets/module.php
  modules/atomic-widgets/styles/atomic-component-styles.php
  modules/atomic-widgets/styles/atomic-widget-styles.php
  modules/atomic-widgets/utils.php
  tests/phpunit/elementor/modules/atomic-widgets/styles/test-atomic-component-styles.php
  tests/phpunit/elementor/modules/atomic-widgets/test-cache-validity.php
Labels: 🚨 10 Unresolved Thread(s), 30 min review

#32095 Internal: Define available units for different controls
  modules/atomic-widgets/prop-types/css-filter-func-prop-type.php
  modules/atomic-widgets/prop-types/dimensions-prop-type.php
  modules/atomic-widgets/prop-types/position-prop-type.php
  modules/atomic-widgets/prop-types/shadow-prop-type.php
  modules/atomic-widgets/prop-types/size-prop-type.php
  modules/atomic-widgets/prop-types/stroke-prop-type.php
  modules/atomic-widgets/prop-types/transform/transform-move-prop-type.php
  modules/atomic-widgets/styles/size-constants.php
  modules/atomic-widgets/styles/style-schema.php
Labels: 🚨 2 Unresolved Thread(s), 20 min review

#32149 Internal: Use internal test methods to navigate to WordPress/Elementor pages [ED-20320]
  tests/playwright/pages/editor-page.ts
  tests/playwright/pages/wp-admin-page.ts
  tests/playwright/sanity/elementor-menu.test.ts
Labels: run-tests, 5 min review

#32094 Internal: Import settings customization [ED-20040]
  app/modules/import-export-customization/assets/js/export/components/export-complete-summary.js
  app/modules/import-export-customization/assets/js/import/components/import-kit-parts-selection.js
  app/modules/import-export-customization/assets/js/import/context/import-context.js
  app/modules/import-export-customization/assets/js/import/hooks/use-upload-kit.js
  app/modules/import-export-customization/assets/js/import/pages/import-complete.js
  app/modules/import-export-customization/assets/js/shared/components/customization-setting-section.js
  app/modules/import-export-customization/assets/js/shared/components/customization-sub-setting.js
  app/modules/import-export-customization/assets/js/shared/components/kit-parts-selection.js
  app/modules/import-export-customization/assets/js/shared/components/kit-plugins-customization-dialog.js
  app/modules/import-export-customization/assets/js/shared/components/kit-settings-customization-dialog.js
  app/modules/import-export-customization/assets/js/shared/utils/string.js
  app/modules/import-export-customization/assets/js/shared/utils/utils.js
  app/modules/import-export-customization/module.php
  app/modules/import-export-customization/runners/import/site-settings.php
  tests/jest/unit/app/modules/import-export-customization/assets/js/components/customization-setting-section.test.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/components/customization-sub-setting.test.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/export/components/kit-settings-customization-dialog.test.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/shared/components/kit-parts-selection.test.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/shared/components/kit-settings-customization-dialog.test.js
  tests/phpunit/elementor/app/import-export-customization/processes/test-import.php
  tests/phpunit/elementor/app/import-export-customization/test-module.php
Labels: 🗑️ Deleted files, 30 min review

#32159 Revert: Remove-PLG-checks-and-text [EMP-3512] [ED-20338]
  core/admin/admin-notices.php
Labels: 1 min review

#32162 Revert: Remove-PLG-checks-and-text 3.31 [EMP-3512] [ED-20338]
  core/admin/admin-notices.php
Labels: 1 min review

#32156 Internal: Add recently used list for transition popup [ED-19789]
  packages/packages/core/editor-editing-panel/src/components/style-sections/effects-section/effects-section.tsx
  packages/packages/core/editor-editing-panel/src/utils/get-recently-used-styles.ts
  packages/packages/libs/editor-controls/src/controls/transition-control/__tests__/transition-repeater-control.test.tsx
  packages/packages/libs/editor-controls/src/controls/transition-control/transition-repeater-control.tsx
  packages/packages/libs/editor-controls/src/controls/transition-control/transition-selector.tsx
Labels: run-tests, 🚨 2 Unresolved Thread(s), 5 min review

#32151 Fix: Variables form fields refactoring [ED-20226]
  modules/atomic-widgets/prop-types/background-image-position-offset-prop-type.php
  modules/atomic-widgets/prop-types/border-radius-prop-type.php
  modules/atomic-widgets/prop-types/border-width-prop-type.php
  modules/atomic-widgets/prop-types/css-filter-func-prop-type.php
  modules/atomic-widgets/prop-types/drop-shadow-filter-prop-type.php
  modules/atomic-widgets/prop-types/layout-direction-prop-type.php
  modules/atomic-widgets/prop-types/position-prop-type.php
  modules/atomic-widgets/prop-types/size-prop-type.php
  modules/atomic-widgets/prop-types/transform/transform-move-prop-type.php
  modules/atomic-widgets/prop-types/transform/transform-rotate-prop-type.php
  modules/atomic-widgets/prop-types/transform/transform-skew-prop-type.php
  modules/atomic-widgets/styles/style-schema.php
  packages/packages/core/editor-variables/src/components/__tests__/validations.test.tsx
  packages/packages/core/editor-variables/src/components/fields/color-field.tsx
  packages/packages/core/editor-variables/src/components/fields/font-field.tsx
  packages/packages/core/editor-variables/src/components/fields/label-field.tsx
  packages/packages/core/editor-variables/src/components/ui/form-field.tsx
  packages/packages/core/editor-variables/src/components/variable-creation.tsx
  packages/packages/core/editor-variables/src/components/variable-edit.tsx
  packages/packages/core/editor-variables/src/components/variable-restore.tsx
  packages/packages/core/editor-variables/src/variables-registry/create-variable-type-registry.ts
  tests/phpunit/elementor/modules/atomic-widgets/prop-types/test-size-prop-type.php
Labels: 🚨 1 Unresolved Thread(s), 30 min review

#32106 Internal: [V4] remove repeater experiment and update transform configuration
  modules/atomic-widgets/module.php
  packages/packages/core/editor-editing-panel/src/components/style-sections/effects-section/effects-section.tsx
  packages/packages/libs/editor-controls/src/components/unstable-repeater/__tests__/unstable-repeater.test.tsx
  packages/packages/libs/editor-controls/src/components/unstable-repeater/actions/add-item-action.tsx
  packages/packages/libs/editor-controls/src/components/unstable-repeater/actions/disable-item-action.tsx
  packages/packages/libs/editor-controls/src/components/unstable-repeater/actions/duplicate-item-action.tsx
  packages/packages/libs/editor-controls/src/components/unstable-repeater/actions/tooltip-add-item-action.tsx
  packages/packages/libs/editor-controls/src/components/unstable-repeater/context/repeater-context.tsx
  packages/packages/libs/editor-controls/src/components/unstable-repeater/header/header.tsx
  packages/packages/libs/editor-controls/src/components/unstable-repeater/index.ts
  packages/packages/libs/editor-controls/src/components/unstable-repeater/items/edit-item-popover.tsx
  packages/packages/libs/editor-controls/src/components/unstable-repeater/items/item.tsx
  packages/packages/libs/editor-controls/src/components/unstable-repeater/items/items-container.tsx
  packages/packages/libs/editor-controls/src/components/unstable-repeater/items/use-popover.tsx
  packages/packages/libs/editor-controls/src/components/unstable-repeater/types.ts
  packages/packages/libs/editor-controls/src/components/unstable-repeater/unstable-repeater.tsx
  packages/packages/libs/editor-controls/src/controls/__tests__/background-overlay-repeater-content.test.tsx
  packages/packages/libs/editor-controls/src/controls/__tests__/background-overlay-repeater-control.test.tsx
  packages/packages/libs/editor-controls/src/controls/background-control/background-overlay/background-overlay-repeater-control.tsx
  packages/packages/libs/editor-controls/src/controls/transform-control/functions/move.tsx
  packages/packages/libs/editor-controls/src/controls/transform-control/functions/rotate.tsx
  packages/packages/libs/editor-controls/src/controls/transform-control/functions/scale.tsx
  packages/packages/libs/editor-controls/src/controls/transform-control/functions/skew.tsx
  packages/packages/libs/editor-controls/src/controls/transform-control/initial-values.ts
  packages/packages/libs/editor-controls/src/controls/transform-control/transform-content.tsx
  packages/packages/libs/editor-controls/src/controls/transform-control/transform-icon.tsx
  packages/packages/libs/editor-controls/src/controls/transform-control/transform-label.tsx
  packages/packages/libs/editor-controls/src/controls/transform-control/transform-repeater-control.tsx
  packages/packages/libs/editor-controls/src/controls/transform-control/use-transform-tabs-history.tsx
  packages/packages/libs/editor-controls/src/controls/unstable-transform-control/unstable-transform-repeater-control.tsx
  packages/packages/libs/editor-controls/src/index.ts
  packages/packages/libs/editor-props/src/prop-types/background-prop-types/background-overlay.ts
  packages/packages/libs/editor-v1-adapters/src/readers/index.ts
Labels: 🚨 4 Unresolved Thread(s), 🗑️ Deleted files, 30 min review

#32166 Internal: Finalize Mixpanel events for Cloud Templates [ED-20048]
  app/modules/kit-library/assets/js/components/item-header.js
  app/modules/kit-library/assets/js/pages/cloud/connect-screen.js
  app/modules/kit-library/module.php
  app/modules/onboarding/assets/js/pages/account.js
  app/modules/onboarding/assets/js/utils/connect.js
  core/common/modules/connect/apps/library.php
  core/common/modules/events-manager/assets/js/module.js
  modules/ai/assets/js/editor/utils/editor-integration.js
Labels: 1 min review, 🚨 1 Unresolved Thread(s)

#32181 Tweak: Change IE Customization experiment [ED-20224]
  app/app.php
  app/modules/import-export-customization/module.php
  app/modules/import-export/module.php
Labels: 1 min review, 🚨 2 Unresolved Thread(s)

#32051 Internal: Create Base control for the CSS transform [ED-20146]
  modules/atomic-widgets/module.php
  modules/atomic-widgets/prop-types/traits/dimensional-prop-type.php
  modules/atomic-widgets/prop-types/transform/transform-move-prop-type.php
  modules/atomic-widgets/prop-types/transform/transform-origin-prop-type.php
  modules/atomic-widgets/prop-types/transform/transform-rotate-prop-type.php
  modules/atomic-widgets/prop-types/transform/transform-scale-prop-type.php
  modules/atomic-widgets/prop-types/transform/transform-skew-prop-type.php
  modules/atomic-widgets/props-resolver/transformers/styles/transform-origin-transformer.php
  modules/atomic-widgets/styles/style-schema.php
  packages/packages/core/editor-canvas/src/init-style-transformers.ts
  packages/packages/core/editor-canvas/src/transformers/styles/transform-origin-transformer.ts
  packages/packages/core/editor-editing-panel/src/components/style-tab.tsx
  packages/packages/libs/editor-controls/src/components/unstable-repeater/actions/tooltip-add-item-action.tsx
  packages/packages/libs/editor-controls/src/components/unstable-repeater/header/header.tsx
  packages/packages/libs/editor-controls/src/controls/transform-control/transform-base-control.tsx
  packages/packages/libs/editor-controls/src/controls/transform-control/transform-base-controls/transform-origin-control.tsx
  packages/packages/libs/editor-controls/src/index.ts
  packages/packages/libs/editor-props/src/prop-types/index.ts
  packages/packages/libs/editor-props/src/prop-types/transform-prop-types/transform-origin.ts
Labels: missing-jira

#32193 Internal: Remove run-tests label from the PR after first run [ED-20330]
  .github/workflows/create-revert-pr/action.yml
  .github/workflows/playwright.yml
Labels: 1 min review

#32201 Internal: Redundant permission API calls [ED-20122]
  packages/packages/core/editor-site-navigation/src/hooks/use-user.ts
Labels: 1 min review, 🚨 1 Unresolved Thread(s)

#32200 Internal: Fix timeline-widget-addon-for-elementor plugin tester test [ED-20366]
  tests/playwright/sanity/plugin-tester-generator.ts
Labels: 1 min review

#32196 Tweak: Improve Cloud Library quota [ED-19474]
  modules/cloud-library/connect/cloud-library.php
Labels: 1 min review, cp_3.31

#32182 Fix: Icon Box widget - Icon can no longer be aligned left/right [ED-20352]
  assets/dev/scss/frontend/widgets/icon-box.scss
Labels: 1 min review, cp_3.31

#32209 Fix: Visual issues with new repeater
  packages/packages/libs/editor-controls/src/components/section-content.tsx
  packages/packages/libs/editor-controls/src/components/unstable-repeater/actions/tooltip-add-item-action.tsx
  packages/packages/libs/editor-controls/src/components/unstable-repeater/header/header.tsx
  packages/packages/libs/editor-controls/src/controls/background-control/background-overlay/background-overlay-repeater-control.tsx
Labels: 1 min review, 🚨 1 Unresolved Thread(s)

#32212 Fix: Repeater label issues [ED-20368]
  packages/packages/libs/editor-controls/src/components/unstable-repeater/context/repeater-context.tsx
Labels: 1 min review

#32184 Tweak: Remove Cloud library experiment [ED-20248]
  app/assets/js/utils/cloud-kits.js
  app/modules/import-export-customization/assets/js/export/hooks/use-export-kit.js
  app/modules/import-export-customization/module.php
  app/modules/import-export/assets/js/pages/export/export-process/export-process.js
  app/modules/import-export/module.php
  app/modules/kit-library/module.php
  assets/dev/js/editor/components/template-library/component.js
  assets/dev/js/editor/components/template-library/manager.js
  assets/dev/js/editor/editor-base.js
  assets/dev/js/editor/elements/views/container.js
  assets/dev/js/editor/elements/views/section.js
  includes/editor-templates/templates.php
  includes/template-library/manager.php
  modules/atomic-widgets/assets/js/editor/div-block-view.js
  modules/cloud-kit-library/module.php
  modules/cloud-library/module.php
Labels: 10 min review

#32219 Tweak: Improve Cloud Library quota [ED-19474]
  modules/cloud-library/connect/cloud-library.php
Labels: 1 min review

#32217 Fix: Effects repeaters disappear when using size variable[ED-20273]
  packages/packages/libs/editor-props/src/prop-types/filter-prop-types/drop-shadow-filter.ts
  packages/packages/libs/editor-props/src/prop-types/filter-prop-types/filter.ts
  packages/packages/libs/editor-props/src/prop-types/position.ts
  packages/packages/libs/editor-props/src/prop-types/selection-size.ts
  packages/packages/libs/editor-props/src/prop-types/transform-prop-types/move-transform.ts
  packages/packages/libs/editor-props/src/prop-types/transform-prop-types/rotate-transform.ts
  packages/packages/libs/editor-props/src/prop-types/transform-prop-types/skew-transform.ts
  packages/packages/libs/editor-props/src/prop-types/transform-prop-types/transform-origin.ts
Labels: 1 min review

#32228 Fix: Add supported size units in the localised settings[ED-20025]
  modules/atomic-widgets/module.php
Labels: 1 min review

#32230 Fix: Add default units to transformers [ED-19691]
  modules/atomic-widgets/prop-types/selection-size-prop-type.php
  modules/atomic-widgets/prop-types/transform/transform-move-prop-type.php
  modules/atomic-widgets/prop-types/transform/transform-rotate-prop-type.php
  modules/atomic-widgets/prop-types/transform/transform-skew-prop-type.php
  modules/atomic-widgets/styles/size-constants.php
Labels: 1 min review

#32235 Internal: Remove packages docs generator [ED-19035]
  packages/.gitignore
  packages/package-lock.json
  packages/package.json
  packages/packages/core/editor-app-bar/typedoc.config.js
  packages/packages/core/editor-notifications/typedoc.config.js
  packages/packages/core/editor/typedoc.config.js
  packages/packages/libs/env/typedoc.config.js
  packages/packages/libs/locations/typedoc.config.js
  packages/packages/libs/menus/typedoc.config.js
  packages/packages/libs/query/typedoc.config.js
  packages/typedoc/intro.md
  packages/typedoc/typedoc.config.js
  packages/typedoc/typedoc.packages.config.js
Labels: 1 min review, 🗑️ Deleted files

#32121 Fix: Prevent the indications popover from opening in the Repeaters - show the dots [ED-20300]
  packages/packages/core/editor-editing-panel/src/styles-inheritance/components/styles-inheritance-indicator.tsx
  packages/packages/core/editor-editing-panel/src/styles-inheritance/components/styles-inheritance-infotip.tsx
  packages/packages/libs/editor-controls/src/components/unstable-repeater/header/header.tsx
Labels: run-tests

#32245 Tweak: Add Pro capabilities to the settings customization [ED-20223]
  app/modules/import-export-customization/assets/js/module.js
  app/modules/import-export-customization/assets/js/shared/components/kit-settings-customization-dialog.js
  app/modules/import-export-customization/assets/js/shared/registry/base.js
  app/modules/import-export-customization/assets/js/shared/registry/site-settings.js
  app/modules/import-export-customization/assets/js/shared/registry/templates.js
  assets/dev/js/modules/modules.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/import/pages/import-customization.test.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/shared/components/kit-settings-customization-dialog.test.js
Labels: 30 min review, 🚨 8 Unresolved Thread(s)

#32270 Revert "Internal: Revert free-to-Pro promotions - clean up [ED-20036]"
  .grunt-config/webpack.js
  includes/utils.php
  includes/widgets/button.php
  includes/widgets/heading.php
  includes/widgets/image-carousel.php
  includes/widgets/testimonial.php
  includes/widgets/video.php
  modules/promotions/assets/js/react/app-manager.js
  modules/promotions/assets/js/react/app.js
  modules/promotions/assets/js/react/components/promotion-card.js
  modules/promotions/assets/js/react/controls/promotion.js
  modules/promotions/assets/js/react/index.js
  modules/promotions/assets/js/react/module.js
  modules/promotions/controls/promotion-control.php
  modules/promotions/module.php
  modules/promotions/promotion-data.php
  tests/playwright/pages/promotions/helper.ts
  tests/playwright/sanity/modules/promotions/promotions.test.ts
Labels: 🚨 3 Unresolved Thread(s), 30 min review

#32262 New: Variables propType will come from the function [ED-20426]
  packages/packages/core/editor-variables/src/components/variable-creation.tsx
  packages/packages/core/editor-variables/src/components/variable-edit.tsx
  packages/packages/core/editor-variables/src/components/variable-restore.tsx
  packages/packages/core/editor-variables/src/variables-registry/create-variable-type-registry.ts
Labels: 1 min review, 🚨 4 Unresolved Thread(s)

#32266 Internal: Remove PHP DI [ED-20376]
  composer.json
  composer.lock
  core/utils/isolation-manager.php
  elementor.php
  includes/container/config.php
  includes/container/container.php
  includes/plugin.php
  modules/apps/admin-apps-page.php
  modules/atomic-opt-in/welcome-screen.php
  modules/checklist/module.php
  modules/checklist/steps/step-base.php
  modules/home/classes/transformations-manager.php
  php-scoper/dependency-injection-inc.php
  tests/bootstrap.php
  tests/phpunit/elementor/includes/container/test-container.php
  tests/phpunit/elementor/includes/container/traits/trait-test-container.php
Labels: 5 min review, 🗑️ Deleted files

#32183 Tweak: Added accessibility Hint [APP-1307] [ED-19619]
  assets/dev/js/editor/regions/panel/pages/elements/elements.js
  assets/dev/js/editor/regions/panel/pages/elements/views/element.js
  assets/dev/js/editor/utils/promotion.js
  assets/dev/scss/editor/panel/_elements.scss
  core/admin/admin-notices.php
  core/admin/admin.php
  core/editor/loader/common/editor-common-scripts-settings.php
  core/utils/hints.php
  includes/editor-templates/panel-elements.php
  modules/promotions/assets/js/editor/module.js
Labels: 20 min review

#32273 Internal: Expose changes for attributes control
  packages/packages/libs/editor-controls/src/controls/key-value-control.tsx
  packages/packages/libs/editor-controls/src/controls/text-control.tsx
  packages/packages/libs/editor-controls/src/index.ts
Labels: 1 min review

#32214 Tweak: Added content structure hint to heading widget [APP-1790] [ED-20359]
  assets/dev/js/editor/editor-base.js
  assets/dev/js/editor/hints/ally.js
  assets/dev/js/editor/hints/index.js
  core/utils/hints.php
  includes/widgets/heading.php
Labels: 20 min review, 🚨 12 Unresolved Thread(s)

#32291 Internal: Update WordPress versions in php unit tests [ED-20444]
  .github/workflows/phpunit.yml
Labels: 1 min review

#32299 Fix: Atomic elements appears after the atomic widgets [ED-20446]
  core/base/document.php
Labels: 1 min review

#32275 Tweak: Move Import Export customizations to Pro [ED-20410]
  app/modules/import-export-customization/assets/js/shared/components/customization-list-setting-section.js
  app/modules/import-export-customization/assets/js/shared/components/customization-setting-section.js
  app/modules/import-export-customization/assets/js/shared/components/customization-sub-setting.js
  app/modules/import-export-customization/assets/js/shared/components/kit-content-customization-dialog.js
  app/modules/import-export-customization/assets/js/shared/components/kit-customization-dialog.js
  app/modules/import-export-customization/assets/js/shared/components/kit-parts-selection.js
  app/modules/import-export-customization/assets/js/shared/components/kit-plugins-customization-dialog.js
  app/modules/import-export-customization/assets/js/shared/components/kit-settings-customization-dialog.js
  app/modules/import-export-customization/assets/js/shared/components/kit-templates-customization-dialog.js
  app/modules/import-export-customization/assets/js/shared/hooks/use-kit-customization-custom-post-types.js
  app/modules/import-export-customization/assets/js/shared/hooks/use-kit-customization-pages.js
  app/modules/import-export-customization/assets/js/shared/hooks/use-kit-customization-taxonomies.js
  app/modules/import-export-customization/assets/js/shared/hooks/use-kit-plugins.js
  app/modules/import-export-customization/assets/js/shared/kit-content-data.js
  app/modules/import-export-customization/assets/js/shared/registry/customization-dialogs.js
  app/modules/import-export-customization/runners/export/plugins.php
  app/modules/import-export-customization/runners/export/site-settings.php
  app/modules/import-export-customization/runners/export/templates.php
  app/modules/import-export-customization/runners/import/plugins.php
  app/modules/import-export-customization/runners/import/site-settings.php
  app/modules/import-export-customization/runners/import/templates.php
  assets/dev/js/modules/modules.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/components/customization-list-setting-section.test.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/components/customization-setting-section.test.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/components/customization-sub-setting.test.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/shared/components/kit-plugins-customization-dialog.test.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/shared/components/kit-settings-customization-dialog.test.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/shared/components/kit-templates-customization-dialog.test.js
  tests/phpunit/elementor/app/import-export-customization/processes/test-export.php
Labels: 10 min review, 🚨 2 Unresolved Thread(s), 🗑️ Deleted files

#32306 Internal: Normalizing relations between transform inner props
  modules/atomic-widgets/module.php
  modules/atomic-widgets/prop-types/traits/dimensional-prop-type.php
  modules/atomic-widgets/prop-types/transform/functions/transform-move-prop-type.php
  modules/atomic-widgets/prop-types/transform/functions/transform-rotate-prop-type.php
  modules/atomic-widgets/prop-types/transform/functions/transform-scale-prop-type.php
  modules/atomic-widgets/prop-types/transform/functions/transform-skew-prop-type.php
  modules/atomic-widgets/prop-types/transform/transform-functions-prop-type.php
  modules/atomic-widgets/prop-types/transform/transform-prop-type.php
  modules/atomic-widgets/prop-types/transform/transform-rotate-prop-type.php
  modules/atomic-widgets/prop-types/transform/transform-skew-prop-type.php
  modules/atomic-widgets/props-resolver/transformers/styles/transform-functions-transformer.php
  modules/atomic-widgets/styles/size-constants.php
  modules/atomic-widgets/styles/style-schema.php
  packages/packages/core/editor-canvas/src/init-style-transformers.ts
  packages/packages/core/editor-canvas/src/transformers/styles/transform-functions-transformer.ts
  packages/packages/core/editor-editing-panel/src/controls-registry/create-top-level-object-type.ts
  packages/packages/core/editor-editing-panel/src/controls-registry/settings-field.tsx
  packages/packages/core/editor-editing-panel/src/controls-registry/styles-field.tsx
  packages/packages/core/editor-editing-panel/src/dynamics/dynamic-control.tsx
  packages/packages/libs/editor-controls/src/controls/transform-control/__tests__/transform-repeater-control.test.tsx
  packages/packages/libs/editor-controls/src/controls/transform-control/functions/axis-row.tsx
  packages/packages/libs/editor-controls/src/controls/transform-control/functions/move.tsx
  packages/packages/libs/editor-controls/src/controls/transform-control/functions/rotate.tsx
  packages/packages/libs/editor-controls/src/controls/transform-control/functions/scale-axis-row.tsx
  packages/packages/libs/editor-controls/src/controls/transform-control/functions/scale.tsx
  packages/packages/libs/editor-controls/src/controls/transform-control/functions/skew.tsx
  packages/packages/libs/editor-controls/src/controls/transform-control/initial-values.ts
  packages/packages/libs/editor-controls/src/controls/transform-control/transform-icon.tsx
  packages/packages/libs/editor-controls/src/controls/transform-control/transform-label.tsx
  packages/packages/libs/editor-controls/src/controls/transform-control/transform-repeater-control.tsx
  packages/packages/libs/editor-controls/src/controls/transform-control/use-transform-tabs-history.tsx
  packages/packages/libs/editor-props/src/prop-types/index.ts
  packages/packages/libs/editor-props/src/prop-types/transform-prop-types/transform-functions.ts
  packages/packages/libs/editor-props/src/prop-types/transform-prop-types/transform-functions/move-transform.ts
  packages/packages/libs/editor-props/src/prop-types/transform-prop-types/transform-functions/rotate-transform.ts
  packages/packages/libs/editor-props/src/prop-types/transform-prop-types/transform-functions/scale-transform.ts
  packages/packages/libs/editor-props/src/prop-types/transform-prop-types/transform-functions/skew-transform.ts
  packages/packages/libs/editor-props/src/prop-types/transform-prop-types/transform.ts
Labels: 🗑️ Deleted files, 30 min review

#32028 Internal: Set conditions cache for Floating Elements [ED-20207]
  modules/floating-buttons/classes/action/action-handler.php
  modules/floating-buttons/classes/conditions/conditions-cache.php
  modules/floating-buttons/module.php
Labels: 10 min review, 🚨 2 Unresolved Thread(s), cp_3.31

#32263 New: Extract form field from label field [ED-20427]
  packages/packages/core/editor-variables/src/components/fields/color-field.tsx
  packages/packages/core/editor-variables/src/components/fields/label-field.tsx
  packages/packages/core/editor-variables/src/components/variable-creation.tsx
  packages/packages/core/editor-variables/src/components/variable-edit.tsx
  packages/packages/core/editor-variables/src/components/variable-restore.tsx
  packages/packages/core/editor-variables/src/components/variables-manager/variable-editable-cell.tsx
  packages/packages/core/editor-variables/src/components/variables-manager/variable-table-cell.tsx
  packages/packages/core/editor-variables/src/components/variables-manager/variables-manager-panel.tsx
  packages/packages/core/editor-variables/src/components/variables-manager/variables-manager-table.tsx
Labels: 10 min review, 🚨 7 Unresolved Thread(s)

#32327 Tweak: Move the plugins customization back to the Core plugin [ED-20411]
  app/modules/import-export-customization/assets/js/shared/components/kit-parts-selection.js
  app/modules/import-export-customization/assets/js/shared/components/kit-plugins-customization-dialog.js
  app/modules/import-export-customization/assets/js/shared/hooks/use-kit-plugins.js
  app/modules/import-export-customization/assets/js/shared/kit-content-data.js
  app/modules/import-export-customization/runners/export/plugins.php
  app/modules/import-export-customization/runners/import/plugins.php
  tests/jest/unit/app/modules/import-export-customization/assets/js/shared/components/kit-plugins-customization-dialog.test.js
Labels: 30 min review

#32364 Internal: Update WP min version on main [ED-20509]
  elementor.php
Labels: 1 min review

#32371 Tweak: Optimize CSS output for Background Videos [ED-20510]
  assets/dev/scss/frontend/_global.scss
Labels: 1 min review

#32375 Internal: Remove createControl from gap and linked controls [ED-20270]
  packages/packages/libs/editor-controls/src/controls/gap-control.tsx
  packages/packages/libs/editor-controls/src/controls/linked-dimensions-control.tsx
Labels: 10 min review

#32382 Internal: Remove duplicate button alignment styles [ED-20516]
  assets/dev/scss/frontend/_global.scss
Labels: run-tests, 1 min review

#32389 Internal: Fix envato-elements plugin [ED-20522]
  tests/playwright/sanity/plugin-tester-generator.ts
Labels: 1 min review

#32377 Tweak: Allow old kits and free users customization capabilities [ED-20414]
  app/modules/import-export-customization/assets/js/import/context/import-context.js
  app/modules/import-export-customization/assets/js/module.js
  app/modules/import-export-customization/assets/js/shared/components/customization-setting-section.js
  app/modules/import-export-customization/assets/js/shared/components/kit-parts-selection.js
  app/modules/import-export-customization/assets/js/shared/components/kit-settings-customization-dialog.js
  app/modules/import-export-customization/assets/js/shared/hooks/use-context-detection.js
  app/modules/import-export-customization/assets/js/shared/kit-content-data.js
  app/modules/import-export-customization/assets/js/shared/registry/site-settings.js
  app/modules/import-export-customization/compatibility/customization.php
  app/modules/import-export-customization/module.php
  app/modules/import-export-customization/runners/export/site-settings.php
  app/modules/import-export-customization/runners/import/site-settings.php
  assets/dev/js/modules/modules.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/export/components/kit-parts-customization.test.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/import/pages/import-customization.test.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/shared/components/kit-parts-selection.test.js
Labels: 🗑️ Deleted files, 30 min review

#32305 Internal: Tests for Variables Manager [ED-20429]
  .cursor/rules/tests-code-style.mdc
  packages/packages/core/editor-variables/src/components/fields/__tests__/label-field.test.tsx
  packages/packages/core/editor-variables/src/components/variables-manager/__tests__/variable-edit-menu.test.tsx
  packages/packages/core/editor-variables/src/components/variables-manager/__tests__/variable-editable-cell.test.tsx
  packages/packages/core/editor-variables/src/components/variables-manager/__tests__/variable-table-cell.test.tsx
  packages/packages/core/editor-variables/src/components/variables-manager/__tests__/variables-manager-panel.test.tsx
  packages/packages/core/editor-variables/src/components/variables-manager/__tests__/variables-manager-table.test.tsx
Labels: 🚨 6 Unresolved Thread(s), 30 min review

#32401 Internal: Create new PropTypes for filters [ED-20394]
  modules/atomic-widgets/module.php
  modules/atomic-widgets/prop-types/filters/backdrop-filter-prop-type.php
  modules/atomic-widgets/prop-types/filters/css-filter-func-prop-type.php
  modules/atomic-widgets/prop-types/filters/filter-prop-type.php
  modules/atomic-widgets/prop-types/filters/functions/blur-prop-type.php
  modules/atomic-widgets/prop-types/filters/functions/color-tone-prop-type.php
  modules/atomic-widgets/prop-types/filters/functions/drop-shadow-filter-prop-type.php
  modules/atomic-widgets/prop-types/filters/functions/hue-rotate-prop-type.php
  modules/atomic-widgets/prop-types/filters/functions/intensity-prop-type.php
  modules/atomic-widgets/styles/size-constants.php
  modules/atomic-widgets/styles/style-schema.php
  packages/packages/libs/editor-props/src/prop-types/filter-prop-types/filter-functions/blur-filter.ts
  packages/packages/libs/editor-props/src/prop-types/filter-prop-types/filter-functions/color-tone-filter.ts
  packages/packages/libs/editor-props/src/prop-types/filter-prop-types/filter-functions/hue-rotate-filter.ts
  packages/packages/libs/editor-props/src/prop-types/filter-prop-types/filter-functions/intensity-filter.ts
  packages/packages/libs/editor-props/src/prop-types/index.ts
Labels: 20 min review

#32415 Fix: Import customization not working from library and cloud kits [ED-20466]
  app/modules/import-export-customization/data/routes/upload.php
Labels: 1 min review

#32411 Internal: Duplicate elements [ED-20500]
  packages/packages/libs/editor-elements/src/hooks/__tests__/use-element-children.test.ts
  packages/packages/libs/editor-elements/src/hooks/use-element-children.ts
  packages/packages/libs/editor-elements/src/index.ts
  packages/packages/libs/editor-elements/src/sync/__tests__/create-elements.test.ts
  packages/packages/libs/editor-elements/src/sync/__tests__/duplicate-elements.test.ts
  packages/packages/libs/editor-elements/src/sync/__tests__/remove-elements.test.ts
  packages/packages/libs/editor-elements/src/sync/create-element.ts
  packages/packages/libs/editor-elements/src/sync/create-elements.ts
  packages/packages/libs/editor-elements/src/sync/duplicate-element.ts
  packages/packages/libs/editor-elements/src/sync/duplicate-elements.ts
  packages/packages/libs/editor-elements/src/sync/remove-elements.ts
  packages/tests/test-utils/create-mock-element-with-children.ts
Labels: 🚨 3 Unresolved Thread(s), 30 min review

#32405 New: Create REST API for components [ED-20334]
  core/utils/api/error-builder.php
  core/utils/api/parse-errors.php
  core/utils/api/parse-result.php
  core/utils/api/response-builder.php
  modules/atomic-widgets/parsers/props-parser.php
  modules/atomic-widgets/parsers/style-parser.php
  modules/components/components-parser.php
  modules/components/components-repository.php
  modules/components/components-rest-api.php
  modules/components/components.php
  modules/components/documents/component.php
  modules/components/module.php
  modules/global-classes/global-classes-parser.php
  modules/global-classes/global-classes-rest-api.php
  tests/phpunit/elementor/modules/atomic-widgets/parsers/test-style-parser.php
  tests/phpunit/elementor/modules/components/mocks/component-1.json
  tests/phpunit/elementor/modules/components/mocks/component-2.json
  tests/phpunit/elementor/modules/components/mocks/component-mocks.php
  tests/phpunit/elementor/modules/components/mocks/invalid-component.json
  tests/phpunit/elementor/modules/components/test-components-rest-api.php
  tests/phpunit/elementor/test-custom-css.php
Labels: 🚨 5 Unresolved Thread(s), 30 min review

#32420 Internal: Update php coding standard rules [ED-20547]
  app/modules/import-export-customization/module.php
  app/modules/import-export-customization/runners/import/site-settings.php
  app/modules/import-export/module.php
  app/modules/import-export/runners/import/site-settings.php
  core/common/modules/finder/categories/create.php
  core/document-types/page-base.php
  core/editor/loader/v1/templates/editor-body-v1-view.php
  core/editor/loader/v2/templates/editor-body-v2-view.php
  core/experiments/manager.php
  includes/editor-templates/editor-wrapper.php
  includes/editor-templates/panel.php
  includes/elements/container.php
  includes/settings/settings.php
  modules/ai/site-planner-connect/view.php
  modules/components/components-rest-api.php
  modules/favorites/module.php
  modules/global-classes/global-classes-rest-api.php
  modules/history/revisions-manager.php
  modules/nested-accordion/widgets/nested-accordion.php
  modules/nested-elements/base/widget-nested-base.php
  modules/nested-tabs/widgets/nested-tabs.php
  modules/variables/classes/rest-api.php
  phpcs.xml
  ruleset.xml
Labels: 10 min review, 🗑️ Deleted files

#32414 Tweak: Merge "Element Caching" feature and move to Performance tab [ED-20208]
  core/admin/admin-notices.php
  core/base/document.php
  modules/element-cache/module.php
Labels: run-tests, 1 min review

#32427 Internal: [V4] Add Post excerpt dynamic tag [ED-20469]
  modules/atomic-widgets/controls/types/number-control.php
  modules/atomic-widgets/dynamic-tags/dynamic-tags-editor-config.php
  modules/atomic-widgets/dynamic-tags/dynamic-tags-module.php
  modules/atomic-widgets/dynamic-tags/dynamic-tags-schemas.php
  packages/packages/core/editor-editing-panel/src/controls-registry/controls-registry.tsx
  packages/packages/libs/editor-controls/src/controls/number-control.tsx
Labels: 10 min review

#32417 Internal: Implement Support for Different Units per Filter Type [ED-20394]
  modules/atomic-widgets/prop-types/filters/css-filter-func-prop-type.php
  packages/packages/core/editor-canvas/src/__tests__/styles-prop-resolver.test.ts
  packages/packages/core/editor-canvas/src/transformers/styles/filter-transformer.ts
  packages/packages/core/editor-variables/src/__tests__/editor-editing-panel-effects/backdrop-filters-drop-shadow.test.tsx
  packages/packages/core/editor-variables/src/__tests__/editor-editing-panel-effects/filters-drop-shadow.test.tsx
  packages/packages/libs/editor-controls/src/controls/__tests__/filter-repeater-control.test.tsx
  packages/packages/libs/editor-controls/src/controls/filter-control/configs.ts
  packages/packages/libs/editor-controls/src/controls/filter-control/context/filter-config-context.tsx
  packages/packages/libs/editor-controls/src/controls/filter-control/drop-shadow/drop-shadow-item-content.tsx
  packages/packages/libs/editor-controls/src/controls/filter-control/drop-shadow/drop-shadow-item-label.tsx
  packages/packages/libs/editor-controls/src/controls/filter-control/filter-content.tsx
  packages/packages/libs/editor-controls/src/controls/filter-control/filter-icon.tsx
  packages/packages/libs/editor-controls/src/controls/filter-control/filter-label.tsx
  packages/packages/libs/editor-controls/src/controls/filter-control/filter-repeater-control.tsx
  packages/packages/libs/editor-controls/src/controls/filter-control/single-size/single-size-item-content.tsx
  packages/packages/libs/editor-controls/src/controls/filter-control/single-size/single-size-item-label.tsx
  packages/packages/libs/editor-controls/src/controls/filter-control/utils.ts
  packages/packages/libs/editor-controls/src/controls/filter-repeater-control.tsx
  packages/packages/libs/editor-controls/src/index.ts
  packages/packages/libs/editor-props/src/prop-types/filter-prop-types/filter.ts
  packages/tests/test-utils/create-mock-filter-schema.ts
Labels: 🚨 4 Unresolved Thread(s), 🗑️ Deleted files, 30 min review

#32443 Internal: Finalizing data & events for the new IE implementation [ED-20225]
  app/assets/js/event-track/apps-event-tracking.js
  app/modules/import-export-customization/assets/js/import/pages/import-complete.js
  app/modules/import-export-customization/assets/js/shared/components/kit-content-customization-dialog.js
  app/modules/import-export-customization/assets/js/shared/components/kit-parts-selection.js
  app/modules/import-export-customization/assets/js/shared/components/kit-plugins-customization-dialog.js
  app/modules/import-export-customization/assets/js/shared/components/kit-settings-customization-dialog.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/import/pages/import-complete.test.js
Labels: 5 min review

#32451 Tweak: Refine Import Export Customization Summary pages [ED-20551]
  app/app.php
  app/modules/import-export-customization/assets/js/export/components/export-complete-download-link.js
  app/modules/import-export-customization/assets/js/export/components/export-complete-heading.js
  app/modules/import-export-customization/assets/js/export/components/export-complete-icon.js
  app/modules/import-export-customization/assets/js/export/components/export-complete-summary.js
  app/modules/import-export-customization/assets/js/export/components/export-intro.js
  app/modules/import-export-customization/assets/js/export/components/export-processing.js
  app/modules/import-export-customization/assets/js/export/pages/export-complete.js
  app/modules/import-export-customization/assets/js/import/pages/import-complete.js
  app/modules/import-export-customization/assets/js/import/pages/import-kit.js
  app/modules/import-export-customization/assets/js/shared/components/complete-heading.js
  app/modules/import-export-customization/assets/js/shared/components/complete-icon.js
  app/modules/import-export-customization/assets/js/shared/components/complete-summary.js
  app/modules/import-export-customization/assets/js/shared/components/download-link.js
  app/modules/import-export-customization/assets/js/shared/components/icons/external-link-icon.js
  app/modules/import-export-customization/assets/js/shared/components/icons/index.js
  app/modules/import-export-customization/assets/js/shared/components/index.js
  app/modules/import-export-customization/assets/js/shared/components/kit-plugins-customization-dialog.js
  app/modules/import-export-customization/assets/js/shared/components/summary-section.js
  app/modules/import-export-customization/assets/js/shared/utils/string.js
  app/modules/import-export-customization/assets/js/shared/utils/utils.js
  app/modules/import-export-customization/module.php
  tests/jest/unit/app/modules/import-export-customization/assets/js/import/pages/import-complete.test.js
Labels: 🗑️ Deleted files, 30 min review

#32418 Internal: Fix accessibility issues in transforms [ED-20534]
  packages/packages/libs/editor-controls/src/components/control-label.tsx
  packages/packages/libs/editor-controls/src/components/size-control/size-input.tsx
  packages/packages/libs/editor-controls/src/components/size-control/text-field-inner-selection.tsx
  packages/packages/libs/editor-controls/src/components/sortable.tsx
  packages/packages/libs/editor-controls/src/components/unstable-repeater/__tests__/unstable-repeater.test.tsx
  packages/packages/libs/editor-controls/src/components/unstable-repeater/actions/tooltip-add-item-action.tsx
  packages/packages/libs/editor-controls/src/controls/__tests__/filter-repeater-control.test.tsx
  packages/packages/libs/editor-controls/src/controls/__tests__/repeatable-control.test.tsx
  packages/packages/libs/editor-controls/src/controls/filter-control/filter-repeater-control.tsx
  packages/packages/libs/editor-controls/src/controls/repeatable-control.tsx
  packages/packages/libs/editor-controls/src/controls/size-control.tsx
  packages/packages/libs/editor-controls/src/controls/transform-control/__tests__/transform-repeater-control.test.tsx
  packages/packages/libs/editor-controls/src/controls/transform-control/functions/axis-row.tsx
  packages/packages/libs/editor-controls/src/controls/transform-control/transform-repeater-control.tsx
  packages/packages/libs/editor-controls/src/controls/transition-control/__tests__/transition-repeater-control.test.tsx
Labels: 10 min review

#32465 Internal: Changelog for GA patc on main [ED-20584]
  changelog.txt
  readme.txt
Labels: 1 min review

#32464 Internal: Changelog for patch on GA [ED-20584]
  changelog.txt
  readme.txt
Labels: 1 min review

#32466 Internal: Deleted variable tooltip if big name [ED-20455]
  packages/packages/core/editor-variables/src/components/ui/delete-confirmation-dialog.tsx
Labels: 1 min review

#32476 Tweak: Old kit import flow tweaks [ED-20589]
  app/modules/import-export-customization/assets/js/shared/components/kit-parts-selection.js
  app/modules/import-export-customization/assets/js/shared/components/re-export-banner.js
  app/modules/import-export-customization/runners/import/elementor-content.php
  app/modules/import-export-customization/runners/import/taxonomies.php
Labels: cp_3.32

#32495 Fix: Apply all when importing from library is not working [ED-20605]
  app/modules/import-export-customization/assets/js/import/context/import-context.js
  app/modules/import-export-customization/assets/js/import/pages/import-kit.js
  app/modules/kit-library/assets/js/components/apply-kit-dialog.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/import/pages/import-kit.test.js
Labels: 10 min review, cp_3.32

#32492 Fix: V4 CSS Editor recreating style variants [ED-20578]
  packages/packages/libs/editor-controls/src/components/css-code-editor/__tests__/css-editor.test.tsx
  packages/packages/libs/editor-controls/src/components/css-code-editor/css-editor.tsx
Labels: 5 min review

#32503 Fix: Export and import all without customization missing the CPT [ED-20595]
  app/modules/import-export-customization/assets/js/shared/hooks/use-kit-customization-custom-post-types.js
Labels: 1 min review

#32509 CI: If statement incorrect fix
  .github/workflows/performance-check.yml
Labels: 1 min review

#32512 Fix: Export site URL [ED-20571]
  app/modules/kit-library/assets/js/pages/cloud/cloud.js
Labels: 1 min review

#32517 Fix: Export and import all without customization missing the CPT [ED-20595]
  app/modules/import-export-customization/assets/js/shared/hooks/use-kit-customization-custom-post-types.js
Labels: 1 min review

#32528 Tweak: Show all exported pages in Import customization [ED-20571]
  app/modules/import-export-customization/runners/export/wp-content.php
  core/utils/import-export/wp-exporter.php
Labels: 1 min review, cp_3.32

#32531 Fix: Plugins checkbox should be disabled in import [ED-20571]
  app/modules/import-export-customization/assets/js/shared/components/kit-parts-selection.js
  tests/jest/unit/app/modules/import-export-customization/assets/js/shared/components/kit-parts-selection.test.js
Labels: 1 min review

#32504 Experiment: Run wp-playground tests on CI
  .github/workflows/pr-pw-tests.yml
  package.json
  tests/playwright/blueprints/ci.json
Labels: missing-jira, 🚨 1 Unresolved Thread(s), 5 min review

#32507 Internal: Add the ability to set Elementor advanced/performance settings in Playwright [ED-20621]
  tests/playwright/pages/wp-admin-page.ts
Labels: run-tests, 1 min review

#32540 Internal: Allow empty values in plain props type if they are not required [ED-20592]
  modules/atomic-widgets/dynamic-tags/dynamic-tags-schemas.php
  modules/atomic-widgets/prop-types/base/plain-prop-type.php
  modules/atomic-widgets/prop-types/concerns/has-required-setting.php
Labels: 1 min review
