Repository elementor/elementor, pull requests merged in 2025-10, with the labels that each got.

#32951 Tweak: On export, retry the media only [ED-21111]
  app/modules/import-export-customization/assets/js/export/components/export-error.js
  app/modules/import-export-customization/assets/js/export/hooks/use-export-kit.js
  app/modules/import-export-customization/assets/js/export/pages/export-process.js
  app/modules/import-export-customization/assets/js/shared/components/error/processing-error-dialog.js
  app/modules/import-export-customization/assets/js/shared/registry/templates.js
  app/modules/import-export-customization/data/routes/process-media.php
  app/modules/import-export-customization/module.php
  assets/dev/js/modules/modules.js
  modules/cloud-kit-library/connect/cloud-kits.php
  tests/jest/unit/app/modules/import-export-customization/assets/js/export/components/export-error.test.js
Labels: 20 min review, 🗑️ Deleted files

#32929 Internal: Remove Manu actions rename delete (ED-20931 )
  packages/packages/core/editor-components/src/components/__tests__/components-tab.test.tsx
  packages/packages/core/editor-components/src/components/components-tab/components-item.tsx
Labels: 1 min review

#32936 Feature: Close panels will return to previously selected element [ED-20471]
  packages/package-lock.json
  packages/packages/core/editor-global-classes/src/components/class-manager/class-manager-panel.tsx
  packages/packages/core/editor-panels/package.json
  packages/packages/core/editor-panels/src/__tests__/api.test.tsx
  packages/packages/core/editor-panels/src/api.ts
  packages/packages/core/editor-variables/src/components/variables-manager/variables-manager-panel.tsx
Labels: 🚨 1 Unresolved Thread(s), 20 min review

#32968 Internal: Changelog for core patch 3324 to GA [ED-21178]
  changelog.txt
  readme.txt
Labels: 1 min review

#32971 Internal: Changelog fix for GA [ED-21178]
  changelog.txt
  readme.txt
Labels: 1 min review

#32993 Internal: Fix sending a message on failure [ED-21191]
  .github/workflows/playwright.yml
Labels: 1 min review

#32949 Internal: Update core onboarding flow [ED-21100]
  app/modules/onboarding/api.php
  app/modules/onboarding/assets/js/components/good-to-go-content-a.js
  app/modules/onboarding/assets/js/components/good-to-go-content-b.js
  app/modules/onboarding/assets/js/components/layout/page-content-layout.js
  app/modules/onboarding/assets/js/components/theme-selection-card.js
  app/modules/onboarding/assets/js/components/theme-selection-content-a.js
  app/modules/onboarding/assets/js/components/theme-selection-content-b.js
  app/modules/onboarding/assets/js/pages/good-to-go.js
  app/modules/onboarding/assets/js/pages/good-to-go.scss
  app/modules/onboarding/assets/js/pages/hello-theme.js
  app/modules/onboarding/assets/js/pages/hello-theme.scss
  app/modules/onboarding/assets/js/utils/modules/click-tracker.js
  app/modules/onboarding/assets/js/utils/modules/event-dispatcher.js
  app/modules/onboarding/assets/js/utils/modules/onboarding-tracker.js
  app/modules/onboarding/assets/js/utils/modules/post-onboarding-tracker.js
  app/modules/onboarding/assets/js/utils/modules/storage-manager.js
  app/modules/onboarding/module.php
  modules/atomic-widgets/assets/js/editor/create-atomic-element-base-view.js
Labels: 🚨 1 Unresolved Thread(s), 30 min review, cp_3.32

#33012 Internal: Bump version
  elementor.php
  package.json
Labels: 1 min review

#33011 Internal: Update core onboarding flow data [ED-21100]
  app/modules/onboarding/assets/js/utils/modules/event-dispatcher.js
Labels: 1 min review, cp_3.32

#33010 Fix: Variables manager title [ED-21196]
  packages/packages/core/editor-variables/src/components/variables-manager/__tests__/variables-manager-panel.test.tsx
  packages/packages/core/editor-variables/src/components/variables-manager/variables-manager-panel.tsx
Labels: 1 min review, cp_3.33

#33024 Fix: Fix tests in variables manager title change [ED-21196]
  tests/playwright/sanity/modules/v4-tests/editor-variables/utils.ts
  tests/playwright/sanity/modules/v4-tests/editor-variables/variable-manager.test.ts
  tests/playwright/sanity/modules/v4-tests/editor-variables/variable-manager.test.ts-snapshots/color-variable-screenshot-darwin.png
  tests/playwright/sanity/modules/v4-tests/editor-variables/variable-manager.test.ts-snapshots/color-variable-screenshot-linux.png
Labels: 1 min review, cp_3.33
